/* Generated by           cobc 3.3-dev.0 */
/* Generated from         ADD-A.cbl */
/* Generated at           Feb 28 2026 03:09:21 */
/* GnuCOBOL build date    Mar 06 2024 10:59:48 */
/* GnuCOBOL package date  Mar 06 2024 09:58:52 UTC */
/* Compile command        C:\Program Files\GnuCOBOL\bin\cobc.exe -x -g ADD-A.cbl */


/* Module path */
static const char		*cob_module_path = NULL;

/* Number of call parameters */
static int		cob_call_params = 0;

/* Attributes */

static const cob_field_attr a_1 =	{0x21,   0,   0, 0x1000, NULL};
static const cob_field_attr a_2 =	{0x21,   0,   0, 0x0000, NULL};
static const cob_field_attr a_3 =	{0x10,   5,   2, 0x0000, NULL};


/* Constants */
static const cob_field c_1	= {20, (cob_u8_ptr)"Inserir valor VAR1: ", &a_1};
static const cob_field c_2	= {45, (cob_u8_ptr)"WS-VAR1 NAO NUMERICO, FAVOR INSERIR NOVAMENTE", &a_1};
static const cob_field c_3	= {20, (cob_u8_ptr)"Inserir valor VAR2: ", &a_1};
static const cob_field c_4	= {45, (cob_u8_ptr)"WS-VAR2 NAO NUMERICO, FAVOR INSERIR NOVAMENTE", &a_1};
static const cob_field c_5	= {20, (cob_u8_ptr)"Inserir valor VAR3: ", &a_1};
static const cob_field c_6	= {45, (cob_u8_ptr)"WS-VAR3 NAO NUMERICO, FAVOR INSERIR NOVAMENTE", &a_1};
static const cob_field c_7	= {20, (cob_u8_ptr)"Inserir valor VAR4: ", &a_1};
static const cob_field c_8	= {45, (cob_u8_ptr)"WS-VAR4 NAO NUMERICO, FAVOR INSERIR NOVAMENTE", &a_1};
static const cob_field c_9	= {30, (cob_u8_ptr)"------------------------------", &a_1};
static const cob_field c_10	= {6, (cob_u8_ptr)"VAR1: ", &a_1};
static const cob_field c_11	= {6, (cob_u8_ptr)"VAR2: ", &a_1};
static const cob_field c_12	= {6, (cob_u8_ptr)"VAR3: ", &a_1};
static const cob_field c_13	= {6, (cob_u8_ptr)"VAR4: ", &a_1};
static const cob_field c_14	= {30, (cob_u8_ptr)"                              ", &a_1};


#define cob_nop	if (!module) cob_nop

