/* Generated by           cobc 3.3-dev.0 */
/* Generated from         ADD-A.cbl */
/* Generated at           Feb 28 2026 03:09:21 */
/* GnuCOBOL build date    Mar 06 2024 10:59:48 */
/* GnuCOBOL package date  Mar 06 2024 09:58:52 UTC */
/* Compile command        C:\Program Files\GnuCOBOL\bin\cobc.exe -x -g ADD-A.cbl */

#include <string.h> /* for memcpy, memcmp and friends */
#define  COB_KEYWORD_INLINE __inline
#include <libcob.h>

#define  COB_SOURCE_FILE		"ADD-A.cbl"
#define  COB_PACKAGE_VERSION		"3.3-dev"
#define  COB_PATCH_LEVEL		0
#define  COB_MODULE_FORMATTED_DATE	"Feb 28 2026 03:09:21"
#define  COB_MODULE_DATE		20260228
#define  COB_MODULE_TIME		30921

/* Global variables */
#include "ADD-A.c.h"

/* Function prototypes */

static int		ADD_A ();
static int		ADD_A_ (const int);
static void		ADD_A_module_init (cob_module *module);

/* Main function */
int
main (int argc, char **argv)
{
  cob_init (argc, argv);
  cob_stop_run (ADD_A ());
}

/* Functions */

static void gc_module_so_init () __attribute__ ((constructor));
static void gc_module_so_init ()
{
  cob_check_version (COB_SOURCE_FILE, COB_PACKAGE_VERSION, COB_PATCH_LEVEL);
}

/* PROGRAM-ID 'ADD_A' */

/* ENTRY 'ADD_A' */

static int
ADD_A ()
{
  return ADD_A_ (0);
}

static int
ADD_A_ (const int entry)
{
  /* Program local variables */
  #include "ADD-A.c.l.h"

  /* Start of function code */

  /* CANCEL callback */
  if (unlikely(entry < 0)) {
  	if (entry == -10)
  		goto P_dump;
  	if (entry == -20)
  		goto P_clear_decimal;
  	goto P_cancel;
  }

  /* Check initialized, check module allocated, */
  /* set global pointer, */
  /* push module stack, save call parameter count */
  if (cob_module_global_enter (&module, &cob_glob_ptr, 0, entry, 0))
  	return -1;

  /* Set address of module parameter list */
  module->cob_procedure_params = cob_procedure_params;

  /* Set frame stack pointer */
  frame_ptr = frame_stack;
  frame_ptr->perform_through = 0;
  frame_ptr->return_address_ptr = &&P_cgerror;
  frame_overflow = frame_ptr + 255 - 1;

  /* Initialize rest of program */
  if (unlikely(initialized == 0)) {
  	goto P_initialize;
  }
  P_ret_initialize:

  /* Increment module active */
  module->module_active++;

  /* Entry dispatch */
  goto l_2;

  /* PROCEDURE DIVISION */

  /* Line: 31        : Entry     ADD_A                   : ADD-A.cbl */
  l_2:;
#line 31 "ADD-A.cbl"
  ENTRY_ADD_A:	cob_nop ();
#line 105 "ADD-A.c"

  /* Line: 31        : Section   S002-INI                : ADD-A.cbl */
#line 31 "ADD-A.cbl"
  SECTION_S002__INI:	cob_nop ();
#line 110 "ADD-A.c"

  /* Line: 32        : Paragraph P002-INI                : ADD-A.cbl */
#line 32 "ADD-A.cbl"
  PARAGRAPH_P002__INI_l_4:	cob_nop ();
#line 115 "ADD-A.c"

  /* Line: 33        : PERFORM            : ADD-A.cbl */
#line 33 "ADD-A.cbl"
  cob_nop ();
#line 120 "ADD-A.c"
  for (;;)
  {
    /* Line: 33        : UNTIL              : ADD-A.cbl */
#line 33 "ADD-A.cbl"
    cob_nop ();
#line 126 "ADD-A.c"
    if (((int)(int)(*(b_26) - (unsigned char)'S') == 0))
      break;
    /* PERFORM P003-VALIDA1 THRU P003-VALIDA1-EXIT */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 9;
    frame_ptr->return_address_ptr = &&l_28;
    goto l_7;
    l_28:
    frame_ptr--;
  }

  /* Line: 34        : SET                : ADD-A.cbl */
#line 34 "ADD-A.cbl"
  cob_nop ();
#line 143 "ADD-A.c"
  *(b_26) = 78;

  /* Line: 35        : PERFORM            : ADD-A.cbl */
#line 35 "ADD-A.cbl"
  cob_nop ();
#line 149 "ADD-A.c"
  for (;;)
  {
    /* Line: 35        : UNTIL              : ADD-A.cbl */
#line 35 "ADD-A.cbl"
    cob_nop ();
#line 155 "ADD-A.c"
    if (((int)(int)(*(b_26) - (unsigned char)'S') == 0))
      break;
    /* PERFORM P003-VALIDA2 THRU P003-VALIDA2-EXIT */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 12;
    frame_ptr->return_address_ptr = &&l_29;
    goto l_10;
    l_29:
    frame_ptr--;
  }

  /* Line: 36        : SET                : ADD-A.cbl */
#line 36 "ADD-A.cbl"
  cob_nop ();
#line 172 "ADD-A.c"
  *(b_26) = 78;

  /* Line: 37        : PERFORM            : ADD-A.cbl */
#line 37 "ADD-A.cbl"
  cob_nop ();
#line 178 "ADD-A.c"
  for (;;)
  {
    /* Line: 37        : UNTIL              : ADD-A.cbl */
#line 37 "ADD-A.cbl"
    cob_nop ();
#line 184 "ADD-A.c"
    if (((int)(int)(*(b_26) - (unsigned char)'S') == 0))
      break;
    /* PERFORM P003-VALIDA3 THRU P003-VALIDA3-EXIT */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 15;
    frame_ptr->return_address_ptr = &&l_30;
    goto l_13;
    l_30:
    frame_ptr--;
  }

  /* Line: 38        : SET                : ADD-A.cbl */
#line 38 "ADD-A.cbl"
  cob_nop ();
#line 201 "ADD-A.c"
  *(b_26) = 78;

  /* Line: 39        : PERFORM            : ADD-A.cbl */
#line 39 "ADD-A.cbl"
  cob_nop ();
#line 207 "ADD-A.c"
  for (;;)
  {
    /* Line: 39        : UNTIL              : ADD-A.cbl */
#line 39 "ADD-A.cbl"
    cob_nop ();
#line 213 "ADD-A.c"
    if (((int)(int)(*(b_26) - (unsigned char)'S') == 0))
      break;
    /* PERFORM P003-VALIDA4 THRU P003-VALIDA4-EXIT */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 18;
    frame_ptr->return_address_ptr = &&l_31;
    goto l_16;
    l_31:
    frame_ptr--;
  }

  /* Line: 41        : PERFORM            : ADD-A.cbl */
#line 41 "ADD-A.cbl"
  cob_nop ();
#line 230 "ADD-A.c"
  /* PERFORM P010-DISPLAY THRU P010-EXIT */
  frame_ptr++;
  if (unlikely(frame_ptr == frame_overflow))
  	cob_fatal_error (COB_FERROR_STACK);
  frame_ptr->perform_through = 24;
  frame_ptr->return_address_ptr = &&l_32;
  goto l_23;
  l_32:
  frame_ptr--;

  /* Line: 42        : PERFORM            : ADD-A.cbl */
#line 42 "ADD-A.cbl"
  cob_nop ();
#line 244 "ADD-A.c"
  /* PERFORM P005-CALCULO THRU P005-EXIT */
  frame_ptr++;
  if (unlikely(frame_ptr == frame_overflow))
  	cob_fatal_error (COB_FERROR_STACK);
  frame_ptr->perform_through = 21;
  frame_ptr->return_address_ptr = &&l_33;
  goto l_20;
  l_33:
  frame_ptr--;

  /* Line: 43        : PERFORM            : ADD-A.cbl */
#line 43 "ADD-A.cbl"
  cob_nop ();
#line 258 "ADD-A.c"
  /* PERFORM P010-DISPLAY THRU P010-EXIT */
  frame_ptr++;
  if (unlikely(frame_ptr == frame_overflow))
  	cob_fatal_error (COB_FERROR_STACK);
  frame_ptr->perform_through = 24;
  frame_ptr->return_address_ptr = &&l_34;
  goto l_23;
  l_34:
  frame_ptr--;

  /* Line: 44        : PERFORM            : ADD-A.cbl */
#line 44 "ADD-A.cbl"
  cob_nop ();
#line 272 "ADD-A.c"
  /* PERFORM P999-TERMINO */
  frame_ptr++;
  if (unlikely(frame_ptr == frame_overflow))
  	cob_fatal_error (COB_FERROR_STACK);
  frame_ptr->perform_through = 26;
  frame_ptr->return_address_ptr = &&l_35;
  goto l_26;
  l_35:
  frame_ptr--;

  /* Line: 45        : Paragraph P002-EXIT               : ADD-A.cbl */
#line 45 "ADD-A.cbl"
  PARAGRAPH_P002__EXIT_l_5:	cob_nop ();
#line 286 "ADD-A.c"

  /* Line: 45        : EXIT               : ADD-A.cbl */
#line 45 "ADD-A.cbl"
  cob_nop ();
#line 291 "ADD-A.c"

  /* Line: 47        : Section   S003-VALIDA             : ADD-A.cbl */
#line 47 "ADD-A.cbl"
  SECTION_S003__VALIDA:	cob_nop ();
#line 296 "ADD-A.c"

  /* Line: 48        : Paragraph P003-VALIDA1            : ADD-A.cbl */
  l_7:;
#line 48 "ADD-A.cbl"
  PARAGRAPH_P003__VALIDA1_l_7:	cob_nop ();
#line 302 "ADD-A.c"

  /* Line: 49        : SET                : ADD-A.cbl */
#line 49 "ADD-A.cbl"
  cob_nop ();
#line 307 "ADD-A.c"
  *(b_26) = 78;

  /* Line: 50        : DISPLAY            : ADD-A.cbl */
#line 50 "ADD-A.cbl"
  cob_nop ();
#line 313 "ADD-A.c"
  cob_display (0, 1, 1, &c_1);

  /* Line: 51        : ACCEPT             : ADD-A.cbl */
#line 51 "ADD-A.cbl"
  cob_nop ();
#line 319 "ADD-A.c"
  cob_accept (&f_18);

  /* Line: 52        : MOVE               : ADD-A.cbl */
#line 52 "ADD-A.cbl"
  cob_nop ();
#line 325 "ADD-A.c"
  cob_move (cob_intr_trim (0, 0, &f_18, 0), &f_18);

  /* Line: 53        : MOVE               : ADD-A.cbl */
#line 53 "ADD-A.cbl"
  cob_nop ();
#line 331 "ADD-A.c"
  cob_move (&f_18, &f_17);

  /* Line: 54        : IF                 : ADD-A.cbl */
#line 54 "ADD-A.cbl"
  cob_nop ();
#line 337 "ADD-A.c"
  if (!cob_is_numeric (&f_17))
  {

    /* Line: 55        : DISPLAY            : ADD-A.cbl */
#line 55 "ADD-A.cbl"
    cob_nop ();
#line 344 "ADD-A.c"
    cob_display (0, 1, 1, &c_2);

    /* Line: 56        : EXIT PARAGRAPH     : ADD-A.cbl */
#line 56 "ADD-A.cbl"
    cob_nop ();
#line 350 "ADD-A.c"
    goto l_8;
  }
  else
  {
    /* ELSE */

    /* Line: 58        : SET                : ADD-A.cbl */
#line 58 "ADD-A.cbl"
    cob_nop ();
#line 360 "ADD-A.c"
    *(b_26) = 83;
  }

  /* Line: 60        : EXIT PARAGRAPH     : ADD-A.cbl */
#line 60 "ADD-A.cbl"
  cob_nop ();
#line 367 "ADD-A.c"
  goto l_8;

  /* Implicit EXIT label */
  l_8:;

  /* Line: 61        : Paragraph P003-VALIDA1-EXIT       : ADD-A.cbl */
  l_9:;
#line 61 "ADD-A.cbl"
  PARAGRAPH_P003__VALIDA1__EXIT_l_9:	cob_nop ();
#line 377 "ADD-A.c"

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 9)
    goto *frame_ptr->return_address_ptr;

  /* Line: 63        : Paragraph P003-VALIDA2            : ADD-A.cbl */
  l_10:;
#line 63 "ADD-A.cbl"
  PARAGRAPH_P003__VALIDA2_l_10:	cob_nop ();
#line 387 "ADD-A.c"

  /* Line: 64        : SET                : ADD-A.cbl */
#line 64 "ADD-A.cbl"
  cob_nop ();
#line 392 "ADD-A.c"
  *(b_26) = 78;

  /* Line: 65        : DISPLAY            : ADD-A.cbl */
#line 65 "ADD-A.cbl"
  cob_nop ();
#line 398 "ADD-A.c"
  cob_display (0, 1, 1, &c_3);

  /* Line: 66        : ACCEPT             : ADD-A.cbl */
#line 66 "ADD-A.cbl"
  cob_nop ();
#line 404 "ADD-A.c"
  cob_accept (&f_20);

  /* Line: 67        : MOVE               : ADD-A.cbl */
#line 67 "ADD-A.cbl"
  cob_nop ();
#line 410 "ADD-A.c"
  cob_move (cob_intr_trim (0, 0, &f_20, 0), &f_20);

  /* Line: 68        : MOVE               : ADD-A.cbl */
#line 68 "ADD-A.cbl"
  cob_nop ();
#line 416 "ADD-A.c"
  cob_move (&f_20, &f_19);

  /* Line: 69        : IF                 : ADD-A.cbl */
#line 69 "ADD-A.cbl"
  cob_nop ();
#line 422 "ADD-A.c"
  if (!cob_is_numeric (&f_19))
  {

    /* Line: 70        : DISPLAY            : ADD-A.cbl */
#line 70 "ADD-A.cbl"
    cob_nop ();
#line 429 "ADD-A.c"
    cob_display (0, 1, 1, &c_4);

    /* Line: 71        : EXIT PARAGRAPH     : ADD-A.cbl */
#line 71 "ADD-A.cbl"
    cob_nop ();
#line 435 "ADD-A.c"
    goto l_11;
  }
  else
  {
    /* ELSE */

    /* Line: 73        : SET                : ADD-A.cbl */
#line 73 "ADD-A.cbl"
    cob_nop ();
#line 445 "ADD-A.c"
    *(b_26) = 83;
  }

  /* Line: 75        : EXIT PARAGRAPH     : ADD-A.cbl */
#line 75 "ADD-A.cbl"
  cob_nop ();
#line 452 "ADD-A.c"
  goto l_11;

  /* Implicit EXIT label */
  l_11:;

  /* Line: 76        : Paragraph P003-VALIDA2-EXIT       : ADD-A.cbl */
  l_12:;
#line 76 "ADD-A.cbl"
  PARAGRAPH_P003__VALIDA2__EXIT_l_12:	cob_nop ();
#line 462 "ADD-A.c"

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 12)
    goto *frame_ptr->return_address_ptr;

  /* Line: 78        : Paragraph P003-VALIDA3            : ADD-A.cbl */
  l_13:;
#line 78 "ADD-A.cbl"
  PARAGRAPH_P003__VALIDA3_l_13:	cob_nop ();
#line 472 "ADD-A.c"

  /* Line: 79        : SET                : ADD-A.cbl */
#line 79 "ADD-A.cbl"
  cob_nop ();
#line 477 "ADD-A.c"
  *(b_26) = 78;

  /* Line: 80        : DISPLAY            : ADD-A.cbl */
#line 80 "ADD-A.cbl"
  cob_nop ();
#line 483 "ADD-A.c"
  cob_display (0, 1, 1, &c_5);

  /* Line: 81        : ACCEPT             : ADD-A.cbl */
#line 81 "ADD-A.cbl"
  cob_nop ();
#line 489 "ADD-A.c"
  cob_accept (&f_22);

  /* Line: 82        : MOVE               : ADD-A.cbl */
#line 82 "ADD-A.cbl"
  cob_nop ();
#line 495 "ADD-A.c"
  cob_move (cob_intr_trim (0, 0, &f_22, 0), &f_22);

  /* Line: 83        : MOVE               : ADD-A.cbl */
#line 83 "ADD-A.cbl"
  cob_nop ();
#line 501 "ADD-A.c"
  cob_move (&f_22, &f_21);

  /* Line: 84        : IF                 : ADD-A.cbl */
#line 84 "ADD-A.cbl"
  cob_nop ();
#line 507 "ADD-A.c"
  if (!cob_is_numeric (&f_21))
  {

    /* Line: 85        : DISPLAY            : ADD-A.cbl */
#line 85 "ADD-A.cbl"
    cob_nop ();
#line 514 "ADD-A.c"
    cob_display (0, 1, 1, &c_6);

    /* Line: 86        : EXIT PARAGRAPH     : ADD-A.cbl */
#line 86 "ADD-A.cbl"
    cob_nop ();
#line 520 "ADD-A.c"
    goto l_14;
  }
  else
  {
    /* ELSE */

    /* Line: 88        : SET                : ADD-A.cbl */
#line 88 "ADD-A.cbl"
    cob_nop ();
#line 530 "ADD-A.c"
    *(b_26) = 83;
  }

  /* Line: 90        : EXIT PARAGRAPH     : ADD-A.cbl */
#line 90 "ADD-A.cbl"
  cob_nop ();
#line 537 "ADD-A.c"
  goto l_14;

  /* Implicit EXIT label */
  l_14:;

  /* Line: 91        : Paragraph P003-VALIDA3-EXIT       : ADD-A.cbl */
  l_15:;
#line 91 "ADD-A.cbl"
  PARAGRAPH_P003__VALIDA3__EXIT_l_15:	cob_nop ();
#line 547 "ADD-A.c"

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 15)
    goto *frame_ptr->return_address_ptr;

  /* Line: 93        : Paragraph P003-VALIDA4            : ADD-A.cbl */
  l_16:;
#line 93 "ADD-A.cbl"
  PARAGRAPH_P003__VALIDA4_l_16:	cob_nop ();
#line 557 "ADD-A.c"

  /* Line: 94        : SET                : ADD-A.cbl */
#line 94 "ADD-A.cbl"
  cob_nop ();
#line 562 "ADD-A.c"
  *(b_26) = 78;

  /* Line: 95        : DISPLAY            : ADD-A.cbl */
#line 95 "ADD-A.cbl"
  cob_nop ();
#line 568 "ADD-A.c"
  cob_display (0, 1, 1, &c_7);

  /* Line: 96        : ACCEPT             : ADD-A.cbl */
#line 96 "ADD-A.cbl"
  cob_nop ();
#line 574 "ADD-A.c"
  cob_accept (&f_24);

  /* Line: 97        : MOVE               : ADD-A.cbl */
#line 97 "ADD-A.cbl"
  cob_nop ();
#line 580 "ADD-A.c"
  cob_move (cob_intr_trim (0, 0, &f_24, 0), &f_24);

  /* Line: 98        : MOVE               : ADD-A.cbl */
#line 98 "ADD-A.cbl"
  cob_nop ();
#line 586 "ADD-A.c"
  cob_move (&f_24, &f_23);

  /* Line: 99        : IF                 : ADD-A.cbl */
#line 99 "ADD-A.cbl"
  cob_nop ();
#line 592 "ADD-A.c"
  if (!cob_is_numeric (&f_23))
  {

    /* Line: 100       : DISPLAY            : ADD-A.cbl */
#line 100 "ADD-A.cbl"
    cob_nop ();
#line 599 "ADD-A.c"
    cob_display (0, 1, 1, &c_8);

    /* Line: 101       : EXIT PARAGRAPH     : ADD-A.cbl */
#line 101 "ADD-A.cbl"
    cob_nop ();
#line 605 "ADD-A.c"
    goto l_17;
  }
  else
  {
    /* ELSE */

    /* Line: 103       : SET                : ADD-A.cbl */
#line 103 "ADD-A.cbl"
    cob_nop ();
#line 615 "ADD-A.c"
    *(b_26) = 83;
  }

  /* Line: 105       : EXIT PARAGRAPH     : ADD-A.cbl */
#line 105 "ADD-A.cbl"
  cob_nop ();
#line 622 "ADD-A.c"
  goto l_17;

  /* Implicit EXIT label */
  l_17:;

  /* Line: 106       : Paragraph P003-VALIDA4-EXIT       : ADD-A.cbl */
  l_18:;
#line 106 "ADD-A.cbl"
  PARAGRAPH_P003__VALIDA4__EXIT_l_18:	cob_nop ();
#line 632 "ADD-A.c"

  /* Line: 107       : EXIT               : ADD-A.cbl */
#line 107 "ADD-A.cbl"
  cob_nop ();
#line 637 "ADD-A.c"

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 18)
    goto *frame_ptr->return_address_ptr;

  /* Line: 109       : Section   S005-CALC               : ADD-A.cbl */
#line 109 "ADD-A.cbl"
  SECTION_S005__CALC:	cob_nop ();
#line 646 "ADD-A.c"

  /* Line: 110       : Paragraph P005-CALCULO            : ADD-A.cbl */
  l_20:;
#line 110 "ADD-A.cbl"
  PARAGRAPH_P005__CALCULO_l_20:	cob_nop ();
#line 652 "ADD-A.c"

  /* Line: 111       : ADD                : ADD-A.cbl */
#line 111 "ADD-A.cbl"
  cob_nop ();
#line 657 "ADD-A.c"
  cob_add (&f_19, &f_17, 0);

  /* Line: 112       : ADD                : ADD-A.cbl */
#line 112 "ADD-A.cbl"
  cob_nop ();
#line 663 "ADD-A.c"
  cob_add (&f_21, &f_19, 0);

  /* Line: 113       : ADD                : ADD-A.cbl */
#line 113 "ADD-A.cbl"
  cob_nop ();
#line 669 "ADD-A.c"
  cob_add (&f_23, &f_21, 0);

  /* Line: 115       : Paragraph P005-EXIT               : ADD-A.cbl */
  l_21:;
#line 115 "ADD-A.cbl"
  PARAGRAPH_P005__EXIT_l_21:	cob_nop ();
#line 676 "ADD-A.c"

  /* Line: 116       : EXIT               : ADD-A.cbl */
#line 116 "ADD-A.cbl"
  cob_nop ();
#line 681 "ADD-A.c"

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 21)
    goto *frame_ptr->return_address_ptr;

  /* Line: 118       : Section   S010-DIS                : ADD-A.cbl */
#line 118 "ADD-A.cbl"
  SECTION_S010__DIS:	cob_nop ();
#line 690 "ADD-A.c"

  /* Line: 119       : Paragraph P010-DISPLAY            : ADD-A.cbl */
  l_23:;
#line 119 "ADD-A.cbl"
  PARAGRAPH_P010__DISPLAY_l_23:	cob_nop ();
#line 696 "ADD-A.c"

  /* Line: 120       : DISPLAY            : ADD-A.cbl */
#line 120 "ADD-A.cbl"
  cob_nop ();
#line 701 "ADD-A.c"
  cob_display (0, 1, 1, &c_9);

  /* Line: 121       : DISPLAY            : ADD-A.cbl */
#line 121 "ADD-A.cbl"
  cob_nop ();
#line 707 "ADD-A.c"
  cob_display (0, 1, 1, &f_25);

  /* Line: 122       : DISPLAY            : ADD-A.cbl */
#line 122 "ADD-A.cbl"
  cob_nop ();
#line 713 "ADD-A.c"
  cob_display (0, 1, 1, &c_9);

  /* Line: 123       : DISPLAY            : ADD-A.cbl */
#line 123 "ADD-A.cbl"
  cob_nop ();
#line 719 "ADD-A.c"
  cob_display (0, 1, 2, &c_10, &f_17);

  /* Line: 124       : DISPLAY            : ADD-A.cbl */
#line 124 "ADD-A.cbl"
  cob_nop ();
#line 725 "ADD-A.c"
  cob_display (0, 1, 2, &c_11, &f_19);

  /* Line: 125       : DISPLAY            : ADD-A.cbl */
#line 125 "ADD-A.cbl"
  cob_nop ();
#line 731 "ADD-A.c"
  cob_display (0, 1, 2, &c_12, &f_21);

  /* Line: 126       : DISPLAY            : ADD-A.cbl */
#line 126 "ADD-A.cbl"
  cob_nop ();
#line 737 "ADD-A.c"
  cob_display (0, 1, 2, &c_13, &f_23);

  /* Line: 127       : DISPLAY            : ADD-A.cbl */
#line 127 "ADD-A.cbl"
  cob_nop ();
#line 743 "ADD-A.c"
  cob_display (0, 1, 1, &c_9);

  /* Line: 128       : DISPLAY            : ADD-A.cbl */
#line 128 "ADD-A.cbl"
  cob_nop ();
#line 749 "ADD-A.c"
  cob_display (0, 1, 1, &c_14);

  /* Line: 129       : Paragraph P010-EXIT               : ADD-A.cbl */
  l_24:;
#line 129 "ADD-A.cbl"
  PARAGRAPH_P010__EXIT_l_24:	cob_nop ();
#line 756 "ADD-A.c"

  /* Line: 130       : EXIT               : ADD-A.cbl */
#line 130 "ADD-A.cbl"
  cob_nop ();
#line 761 "ADD-A.c"

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 24)
    goto *frame_ptr->return_address_ptr;

  /* Line: 132       : Section   S900-TERM               : ADD-A.cbl */
#line 132 "ADD-A.cbl"
  SECTION_S900__TERM:	cob_nop ();
#line 770 "ADD-A.c"

  /* Line: 133       : Paragraph P999-TERMINO            : ADD-A.cbl */
  l_26:;
#line 133 "ADD-A.cbl"
  PARAGRAPH_P999__TERMINO_l_26:	cob_nop ();
#line 776 "ADD-A.c"

  /* Line: 134       : STOP RUN           : ADD-A.cbl */
#line 134 "ADD-A.cbl"
  cob_nop ();
#line 781 "ADD-A.c"
  cob_stop_run (b_2);

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 26)
    goto *frame_ptr->return_address_ptr;

  /* Line: 135       : Paragraph P999-EXIT               : ADD-A.cbl */
#line 135 "ADD-A.cbl"
  PARAGRAPH_P999__EXIT_l_27:	cob_nop ();
#line 791 "ADD-A.c"

  /* Line: 136       : EXIT               : ADD-A.cbl */
#line 136 "ADD-A.cbl"
  cob_nop ();
#line 796 "ADD-A.c"

  /* Program exit */

  exit_program:

  /* Decrement module active count */
  if (module->module_active) {
  	module->module_active--;
  }

  /* Pop module stack */
  cob_module_leave (module);

  /* Program return */
  return b_2;
  P_cgerror:
  	cob_fatal_error (COB_FERROR_CODEGEN);


  /* Program initialization */
  P_initialize:

  cob_module_path = cob_glob_ptr->cob_main_argv0;

  ADD_A_module_init (module);

  module->collating_sequence = NULL;
  module->crt_status = NULL;
  module->cursor_pos = NULL;
  module->xml_code = NULL;
  module->xml_event = NULL;
  module->xml_information = NULL;
  module->xml_namespace = NULL;
  module->xml_namespace_prefix = NULL;
  module->xml_nnamespace = NULL;
  module->xml_nnamespace_prefix = NULL;
  module->xml_ntext = NULL;
  module->xml_text = NULL;
  module->json_code = NULL;
  module->json_status = NULL;

  /* Initialize cancel callback */
  cob_set_cancel (module);

  /* Initialize WORKING-STORAGE */
  /* initialize field RETURN-CODE */
  b_2 = 0;

  /* initialize field WS-VAR1 */
#line 15 "ADD-A.cbl"
  cob_nop ();
#line 848 "ADD-A.c"
  memset (b_17, 48, 5);

  /* initialize field WS-VAR1-TEXTO */
#line 16 "ADD-A.cbl"
  cob_nop ();
#line 854 "ADD-A.c"
  memset (b_18, 32, 5);

  /* initialize field WS-VAR2 */
#line 17 "ADD-A.cbl"
  cob_nop ();
#line 860 "ADD-A.c"
  memset (b_19, 48, 5);

  /* initialize field WS-VAR2-TEXTO */
#line 18 "ADD-A.cbl"
  cob_nop ();
#line 866 "ADD-A.c"
  memset (b_20, 32, 5);

  /* initialize field WS-VAR3 */
#line 19 "ADD-A.cbl"
  cob_nop ();
#line 872 "ADD-A.c"
  memset (b_21, 48, 5);

  /* initialize field WS-VAR3-TEXTO */
#line 20 "ADD-A.cbl"
  cob_nop ();
#line 878 "ADD-A.c"
  memset (b_22, 32, 5);

  /* initialize field WS-VAR4 */
#line 21 "ADD-A.cbl"
  cob_nop ();
#line 884 "ADD-A.c"
  memset (b_23, 48, 5);

  /* initialize field WS-VAR4-TEXTO */
#line 22 "ADD-A.cbl"
  cob_nop ();
#line 890 "ADD-A.c"
  memset (b_24, 32, 5);

  /* initialize field WS-TEXTO */
#line 23 "ADD-A.cbl"
  cob_nop ();
#line 896 "ADD-A.c"
  memset (b_25, 32, 30);

  /* initialize field WS-OK */
#line 26 "ADD-A.cbl"
  cob_nop ();
#line 902 "ADD-A.c"
  *(cob_u8_ptr)(b_26) = (unsigned char)'N';


  if (0 == 1) goto P_cgerror;
  initialized = 1;
  goto P_ret_initialize;

  P_dump:
    return 0;


  /* CANCEL callback handling */
  P_cancel:

  if (!initialized)
  	return 0;
  if (module && module->module_active)
  	cob_fatal_error (COB_FERROR_CANCEL);

  initialized = 0;

  P_clear_decimal:
  return 0;

}

/* End PROGRAM-ID 'ADD_A' */

/* Initialize module structure for ADD_A */
static void ADD_A_module_init (cob_module *module)
{
  module->module_name = "ADD_A";
  module->module_formatted_date = COB_MODULE_FORMATTED_DATE;
  module->module_source = COB_SOURCE_FILE;
  module->gc_version = COB_PACKAGE_VERSION;
  module->module_entry.funcptr = (void *(*)())ADD_A;
  module->module_cancel.funcptr = (void *(*)())ADD_A_;
  module->module_ref_count = NULL;
  module->module_path = &cob_module_path;
  module->module_active = 0;
  module->module_date = COB_MODULE_DATE;
  module->module_time = COB_MODULE_TIME;
  module->module_type = 0;
  module->module_param_cnt = 0;
  module->ebcdic_sign = 0;
  module->decimal_point = ',';
  module->currency_symbol = '$';
  module->numeric_separator = '.';
  module->flag_filename_mapping = 1;
  module->flag_binary_truncate = 1;
  module->flag_pretty_display = 1;
  module->flag_host_sign = 0;
  module->flag_no_phys_canc = 1;
  module->flag_main = 1;
  module->flag_fold_call = 0;
  module->flag_exit_program = 0;
  module->flag_debug_trace = 0;
  module->flag_dump_ready = 0;
  module->xml_mode = 1;
  module->module_stmt = 0;
  module->module_sources = NULL;
}

/* End functions */

