/* Generated by           cobc 3.3-dev.0 */
/* Generated from         ADD-CORR.cbl */
/* Generated at           Mar 08 2026 10:38:36 */
/* GnuCOBOL build date    Mar 06 2024 10:59:48 */
/* GnuCOBOL package date  Mar 06 2024 09:58:52 UTC */
/* Compile command        C:\Program Files\GnuCOBOL\bin\cobc.exe -x -g ADD-CORR.cbl */


/* Module path */
static const char		*cob_module_path = NULL;

/* Number of call parameters */
static int		cob_call_params = 0;

/* Attributes */

static const cob_field_attr a_1 =	{0x10,   2,   0, 0x0000, NULL};
static const cob_field_attr a_2 =	{0x21,   0,   0, 0x1000, NULL};
static const cob_field_attr a_3 =	{0x01,   0,   0, 0x0000, NULL};


/* Constants */
static const cob_field c_1	= {10, (cob_u8_ptr)"WS-REG-1: ", &a_2};
static const cob_field c_2	= {10, (cob_u8_ptr)"WS-REG-2: ", &a_2};


#define cob_nop	if (!module) cob_nop


static int COB_INLINE COB_A_INLINE
cob_get_numdisp (const void *data, const int size)
{
	register const unsigned char	*p = (const unsigned char *)data;
	register int	n;
	register int	val = 0;
	for (n = 0; n < size; ++n) {
		if (*p & 0x0F)
			break;
		p++;
	}
	for (; n < size; ++n, ++p) {
		val = (val * 10)
		    + (*p & 0x0F);
	}
	return val;
}

