/* Generated by           cobc 3.3-dev.0 */
/* Generated from         ADD-A.cbl */
/* Generated at           Feb 28 2026 03:09:21 */
/* GnuCOBOL build date    Mar 06 2024 10:59:48 */
/* GnuCOBOL package date  Mar 06 2024 09:58:52 UTC */
/* Compile command        C:\Program Files\GnuCOBOL\bin\cobc.exe -x -g ADD-A.cbl */

/* Program local variables for 'ADD_A' */

/* Module initialization indicator */
static unsigned int	initialized = 0;

/* Module structure pointer */
static cob_module	*module = NULL;

/* Global variable pointer */
cob_global		*cob_glob_ptr;


/* LINKAGE SECTION (Items not referenced by USING clause) */
static unsigned char	*b_9 = NULL;  /* XML-NAMESPACE */
static unsigned char	*b_10 = NULL;  /* XML-NAMESPACE-PREFIX */
static unsigned char	*b_11 = NULL;  /* XML-NNAMESPACE */
static unsigned char	*b_12 = NULL;  /* XML-NNAMESPACE-PREFIX */
static unsigned char	*b_13 = NULL;  /* XML-NTEXT */
static unsigned char	*b_14 = NULL;  /* XML-TEXT */


/* Call parameters */
cob_field		*cob_procedure_params[1];

/* Perform frame stack */
struct cob_frame	*frame_overflow;
struct cob_frame	*frame_ptr;
struct cob_frame	frame_stack[255];


/* Data storage */
static int	b_2;	/* RETURN-CODE */
static cob_u8_t	b_17[5] __attribute__((aligned));	/* WS-VAR1 */
static cob_u8_t	b_18[5] __attribute__((aligned));	/* WS-VAR1-TEXTO */
static cob_u8_t	b_19[5] __attribute__((aligned));	/* WS-VAR2 */
static cob_u8_t	b_20[5] __attribute__((aligned));	/* WS-VAR2-TEXTO */
static cob_u8_t	b_21[5] __attribute__((aligned));	/* WS-VAR3 */
static cob_u8_t	b_22[5] __attribute__((aligned));	/* WS-VAR3-TEXTO */
static cob_u8_t	b_23[5] __attribute__((aligned));	/* WS-VAR4 */
static cob_u8_t	b_24[5] __attribute__((aligned));	/* WS-VAR4-TEXTO */
static cob_u8_t	b_25[30] __attribute__((aligned));	/* WS-TEXTO */
static cob_u8_t	b_26[1] __attribute__((aligned));	/* WS-STATUS */

/* End of local data storage */


/* Fields (local) */
static cob_field f_17	= {5, b_17, &a_3};	/* WS-VAR1 */
static cob_field f_18	= {5, b_18, &a_2};	/* WS-VAR1-TEXTO */
static cob_field f_19	= {5, b_19, &a_3};	/* WS-VAR2 */
static cob_field f_20	= {5, b_20, &a_2};	/* WS-VAR2-TEXTO */
static cob_field f_21	= {5, b_21, &a_3};	/* WS-VAR3 */
static cob_field f_22	= {5, b_22, &a_2};	/* WS-VAR3-TEXTO */
static cob_field f_23	= {5, b_23, &a_3};	/* WS-VAR4 */
static cob_field f_24	= {5, b_24, &a_2};	/* WS-VAR4-TEXTO */
static cob_field f_25	= {30, b_25, &a_2};	/* WS-TEXTO */

/* End of fields */

