/* Generated by           cobc 3.3-dev.0 */
/* Generated from         ADD-CORR.cbl */
/* Generated at           Mar 08 2026 10:38:36 */
/* GnuCOBOL build date    Mar 06 2024 10:59:48 */
/* GnuCOBOL package date  Mar 06 2024 09:58:52 UTC */
/* Compile command        C:\Program Files\GnuCOBOL\bin\cobc.exe -x -g ADD-CORR.cbl */

#include <string.h> /* for memcpy, memcmp and friends */
#define  COB_KEYWORD_INLINE __inline
#include <libcob.h>

#define  COB_SOURCE_FILE		"ADD-CORR.cbl"
#define  COB_PACKAGE_VERSION		"3.3-dev"
#define  COB_PATCH_LEVEL		0
#define  COB_MODULE_FORMATTED_DATE	"Mar 08 2026 10:38:36"
#define  COB_MODULE_DATE		20260308
#define  COB_MODULE_TIME		103836

/* Global variables */
#include "ADD-CORR.c.h"

/* Function prototypes */

static int		ADD__CORR ();
static int		ADD__CORR_ (const int);
static void		ADD__CORR_module_init (cob_module *module);

/* Main function */
int
main (int argc, char **argv)
{
  cob_init (argc, argv);
  cob_stop_run (ADD__CORR ());
}

/* Functions */

static void gc_module_so_init () __attribute__ ((constructor));
static void gc_module_so_init ()
{
  cob_check_version (COB_SOURCE_FILE, COB_PACKAGE_VERSION, COB_PATCH_LEVEL);
}

/* PROGRAM-ID 'ADD-CORR' */

/* ENTRY 'ADD__CORR' */

static int
ADD__CORR ()
{
  return ADD__CORR_ (0);
}

static int
ADD__CORR_ (const int entry)
{
  /* Program local variables */
  #include "ADD-CORR.c.l.h"

  /* Start of function code */

  /* CANCEL callback */
  if (unlikely(entry < 0)) {
  	if (entry == -10)
  		goto P_dump;
  	if (entry == -20)
  		goto P_clear_decimal;
  	goto P_cancel;
  }

  /* Check initialized, check module allocated, */
  /* set global pointer, */
  /* push module stack, save call parameter count */
  if (cob_module_global_enter (&module, &cob_glob_ptr, 0, entry, 0))
  	return -1;

  /* Set address of module parameter list */
  module->cob_procedure_params = cob_procedure_params;

  /* Set frame stack pointer */
  frame_ptr = frame_stack;
  frame_ptr->perform_through = 0;
  frame_ptr->return_address_ptr = &&P_cgerror;
  frame_overflow = frame_ptr + 255 - 1;

  /* Initialize rest of program */
  if (unlikely(initialized == 0)) {
  	goto P_initialize;
  }
  P_ret_initialize:

  /* Increment module active */
  module->module_active++;

  /* Entry dispatch */
  goto l_2;

  /* PROCEDURE DIVISION */

  /* Line: 33        : Entry     ADD-CORR                : ADD-CORR.cbl */
  l_2:;
#line 33 "ADD-CORR.cbl"
  ENTRY_ADD__CORR:	cob_nop ();
#line 105 "ADD-CORR.c"

  /* Line: 33        : Section   S000                    : ADD-CORR.cbl */
#line 33 "ADD-CORR.cbl"
  SECTION_S000:	cob_nop ();
#line 110 "ADD-CORR.c"

  /* Line: 34        : Paragraph P001-INICIO             : ADD-CORR.cbl */
#line 34 "ADD-CORR.cbl"
  PARAGRAPH_P001__INICIO_l_4:	cob_nop ();
#line 115 "ADD-CORR.c"

  /* Line: 36        : MOVE               : ADD-CORR.cbl */
#line 36 "ADD-CORR.cbl"
  cob_nop ();
#line 120 "ADD-CORR.c"
  memcpy (b_17, "01CARLOS AUGUSTO 11987879898", 28);

  /* Line: 37        : ADD                : ADD-CORR.cbl */
#line 37 "ADD-CORR.cbl"
  cob_nop ();
#line 126 "ADD-CORR.c"
  cob_add_int (&f_22, cob_get_numdisp (b_17, 2), 0);

  /* Line: 38        : MOVE               : ADD-CORR.cbl */
#line 38 "ADD-CORR.cbl"
  cob_nop ();
#line 132 "ADD-CORR.c"
  memcpy (b_21 + 2, b_17 + 2, 15);

  /* Line: 39        : MOVE               : ADD-CORR.cbl */
#line 39 "ADD-CORR.cbl"
  cob_nop ();
#line 138 "ADD-CORR.c"
  memcpy (b_21 + 17, b_17 + 17, 11);

  /* Line: 41        : DISPLAY            : ADD-CORR.cbl */
#line 41 "ADD-CORR.cbl"
  cob_nop ();
#line 144 "ADD-CORR.c"
  cob_display (0, 1, 2, &c_1, &f_17);

  /* Line: 42        : DISPLAY            : ADD-CORR.cbl */
#line 42 "ADD-CORR.cbl"
  cob_nop ();
#line 150 "ADD-CORR.c"
  cob_display (0, 1, 2, &c_2, &f_21);

  /* Line: 44        : ADD                : ADD-CORR.cbl */
#line 44 "ADD-CORR.cbl"
  cob_nop ();
#line 156 "ADD-CORR.c"
  cob_add_int (&f_22, cob_get_numdisp (b_17, 2), 0);

  /* Line: 46        : DISPLAY            : ADD-CORR.cbl */
#line 46 "ADD-CORR.cbl"
  cob_nop ();
#line 162 "ADD-CORR.c"
  cob_display (0, 1, 2, &c_1, &f_17);

  /* Line: 47        : DISPLAY            : ADD-CORR.cbl */
#line 47 "ADD-CORR.cbl"
  cob_nop ();
#line 168 "ADD-CORR.c"
  cob_display (0, 1, 2, &c_2, &f_21);

  /* Line: 49        : MOVE               : ADD-CORR.cbl */
#line 49 "ADD-CORR.cbl"
  cob_nop ();
#line 174 "ADD-CORR.c"
  memcpy (b_25, "05", 2);

  /* Line: 50        : ADD                : ADD-CORR.cbl */
#line 50 "ADD-CORR.cbl"
  cob_nop ();
#line 180 "ADD-CORR.c"
  cob_add_int (&f_22, cob_get_numdisp (b_25, 2), 0);

  /* Line: 52        : DISPLAY            : ADD-CORR.cbl */
#line 52 "ADD-CORR.cbl"
  cob_nop ();
#line 186 "ADD-CORR.c"
  cob_display (0, 1, 2, &c_1, &f_17);

  /* Line: 53        : DISPLAY            : ADD-CORR.cbl */
#line 53 "ADD-CORR.cbl"
  cob_nop ();
#line 192 "ADD-CORR.c"
  cob_display (0, 1, 2, &c_2, &f_21);

  /* Line: 55        : Paragraph P001-EXIT               : ADD-CORR.cbl */
#line 55 "ADD-CORR.cbl"
  PARAGRAPH_P001__EXIT_l_5:	cob_nop ();
#line 198 "ADD-CORR.c"

  /* Line: 56        : EXIT               : ADD-CORR.cbl */
#line 56 "ADD-CORR.cbl"
  cob_nop ();
#line 203 "ADD-CORR.c"

  /* Line: 58        : Section   S900                    : ADD-CORR.cbl */
#line 58 "ADD-CORR.cbl"
  SECTION_S900:	cob_nop ();
#line 208 "ADD-CORR.c"

  /* Line: 59        : Paragraph P901-TERMINO            : ADD-CORR.cbl */
#line 59 "ADD-CORR.cbl"
  PARAGRAPH_P901__TERMINO_l_7:	cob_nop ();
#line 213 "ADD-CORR.c"

  /* Line: 60        : STOP RUN           : ADD-CORR.cbl */
#line 60 "ADD-CORR.cbl"
  cob_nop ();
#line 218 "ADD-CORR.c"
  cob_stop_run (b_2);

  /* Line: 61        : Paragraph P901-EXIT               : ADD-CORR.cbl */
#line 61 "ADD-CORR.cbl"
  PARAGRAPH_P901__EXIT_l_8:	cob_nop ();
#line 224 "ADD-CORR.c"

  /* Line: 62        : EXIT               : ADD-CORR.cbl */
#line 62 "ADD-CORR.cbl"
  cob_nop ();
#line 229 "ADD-CORR.c"

  /* Program exit */

  exit_program:

  /* Decrement module active count */
  if (module->module_active) {
  	module->module_active--;
  }

  /* Pop module stack */
  cob_module_leave (module);

  /* Program return */
  return b_2;
  P_cgerror:
  	cob_fatal_error (COB_FERROR_CODEGEN);


  /* Program initialization */
  P_initialize:

  cob_module_path = cob_glob_ptr->cob_main_argv0;

  ADD__CORR_module_init (module);

  module->collating_sequence = NULL;
  module->crt_status = NULL;
  module->cursor_pos = NULL;
  module->xml_code = NULL;
  module->xml_event = NULL;
  module->xml_information = NULL;
  module->xml_namespace = NULL;
  module->xml_namespace_prefix = NULL;
  module->xml_nnamespace = NULL;
  module->xml_nnamespace_prefix = NULL;
  module->xml_ntext = NULL;
  module->xml_text = NULL;
  module->json_code = NULL;
  module->json_status = NULL;

  /* Initialize cancel callback */
  cob_set_cancel (module);

  /* Initialize WORKING-STORAGE */
  /* initialize field RETURN-CODE */
  b_2 = 0;

  /* initialize field CODIGO */
#line 18 "ADD-CORR.cbl"
  cob_nop ();
#line 281 "ADD-CORR.c"
  memset (b_17, (unsigned char)'0', 2);
  /* initialize field NOME */
#line 19 "ADD-CORR.cbl"
  cob_nop ();
#line 286 "ADD-CORR.c"
  memset (b_17 + 2, (unsigned char)' ', 26);

  /* initialize field CODIGO */
#line 23 "ADD-CORR.cbl"
  cob_nop ();
#line 292 "ADD-CORR.c"
  memset (b_21, (unsigned char)'0', 2);
  /* initialize field NOME */
#line 24 "ADD-CORR.cbl"
  cob_nop ();
#line 297 "ADD-CORR.c"
  memset (b_21 + 2, (unsigned char)' ', 26);

  /* initialize field CODIGO */
#line 28 "ADD-CORR.cbl"
  cob_nop ();
#line 303 "ADD-CORR.c"
  memset (b_25, (unsigned char)'0', 2);
  /* initialize field FILLER 1 */
#line 29 "ADD-CORR.cbl"
  cob_nop ();
#line 308 "ADD-CORR.c"
  memset (b_25 + 2, (unsigned char)' ', 26);


  if (0 == 1) goto P_cgerror;
  initialized = 1;
  goto P_ret_initialize;

  P_dump:
    return 0;


  /* CANCEL callback handling */
  P_cancel:

  if (!initialized)
  	return 0;
  if (module && module->module_active)
  	cob_fatal_error (COB_FERROR_CANCEL);

  initialized = 0;

  P_clear_decimal:
  return 0;

}

/* End PROGRAM-ID 'ADD-CORR' */

/* Initialize module structure for ADD-CORR */
static void ADD__CORR_module_init (cob_module *module)
{
  module->module_name = "ADD-CORR";
  module->module_formatted_date = COB_MODULE_FORMATTED_DATE;
  module->module_source = COB_SOURCE_FILE;
  module->gc_version = COB_PACKAGE_VERSION;
  module->module_entry.funcptr = (void *(*)())ADD__CORR;
  module->module_cancel.funcptr = (void *(*)())ADD__CORR_;
  module->module_ref_count = NULL;
  module->module_path = &cob_module_path;
  module->module_active = 0;
  module->module_date = COB_MODULE_DATE;
  module->module_time = COB_MODULE_TIME;
  module->module_type = 0;
  module->module_param_cnt = 0;
  module->ebcdic_sign = 0;
  module->decimal_point = ',';
  module->currency_symbol = '$';
  module->numeric_separator = '.';
  module->flag_filename_mapping = 1;
  module->flag_binary_truncate = 1;
  module->flag_pretty_display = 1;
  module->flag_host_sign = 0;
  module->flag_no_phys_canc = 1;
  module->flag_main = 1;
  module->flag_fold_call = 0;
  module->flag_exit_program = 0;
  module->flag_debug_trace = 0;
  module->flag_dump_ready = 0;
  module->xml_mode = 1;
  module->module_stmt = 0;
  module->module_sources = NULL;
}

/* End functions */

