/* Generated by           cobc 3.3-dev.0 */
/* Generated from         AMOST51.cbl */
/* Generated at           Mar 08 2026 10:43:02 */
/* GnuCOBOL build date    Mar 06 2024 10:59:48 */
/* GnuCOBOL package date  Mar 06 2024 09:58:52 UTC */
/* Compile command        C:\Program Files\GnuCOBOL\bin\cobc.exe -x -g AMOST51.cbl */


/* Module path */
static const char		*cob_module_path = NULL;

/* Number of call parameters */
static int		cob_call_params = 0;

/* Attributes */

static const cob_field_attr a_1 =	{0x21,   0,   0, 0x1000, NULL};
static const cob_field_attr a_2 =	{0x10,   3,   0, 0x0000, NULL};
static const cob_field_attr a_3 =	{0x10,   2,   0, 0x0000, NULL};


/* Constants */
static const cob_field c_1	= {1, (cob_u8_ptr)" ", &a_1};
static const cob_field c_2	= {20, (cob_u8_ptr)"VALOR MULTIPO 11 => ", &a_1};
static const cob_field c_3	= {11, (cob_u8_ptr)" - INDICE: ", &a_1};
static const cob_field c_4	= {41, (cob_u8_ptr)"QUAL INDICE VC DESEJA VERIFICAR O VALOR\? ", &a_1};
static const cob_field c_5	= {7, (cob_u8_ptr)"VALOR: ", &a_1};


#define cob_nop	if (!module) cob_nop


static int COB_INLINE COB_A_INLINE
cob_get_numdisp (const void *data, const int size)
{
	register const unsigned char	*p = (const unsigned char *)data;
	register int	n;
	register int	val = 0;
	for (n = 0; n < size; ++n) {
		if (*p & 0x0F)
			break;
		p++;
	}
	for (; n < size; ++n, ++p) {
		val = (val * 10)
		    + (*p & 0x0F);
	}
	return val;
}

