/* Generated by           cobc 3.3-dev.0 */
/* Generated from         AMOST51.cbl */
/* Generated at           Mar 08 2026 10:43:02 */
/* GnuCOBOL build date    Mar 06 2024 10:59:48 */
/* GnuCOBOL package date  Mar 06 2024 09:58:52 UTC */
/* Compile command        C:\Program Files\GnuCOBOL\bin\cobc.exe -x -g AMOST51.cbl */

/* Program local variables for 'AMOST51' */

/* Module initialization indicator */
static unsigned int	initialized = 0;

/* Module structure pointer */
static cob_module	*module = NULL;

/* Global variable pointer */
cob_global		*cob_glob_ptr;


/* LINKAGE SECTION (Items not referenced by USING clause) */
static unsigned char	*b_9 = NULL;  /* XML-NAMESPACE */
static unsigned char	*b_10 = NULL;  /* XML-NAMESPACE-PREFIX */
static unsigned char	*b_11 = NULL;  /* XML-NNAMESPACE */
static unsigned char	*b_12 = NULL;  /* XML-NNAMESPACE-PREFIX */
static unsigned char	*b_13 = NULL;  /* XML-NTEXT */
static unsigned char	*b_14 = NULL;  /* XML-TEXT */


/* Local cob_field items */
cob_field		f0;


/* Call parameters */
cob_field		*cob_procedure_params[1];

/* Perform frame stack */
struct cob_frame	*frame_overflow;
struct cob_frame	*frame_ptr;
struct cob_frame	frame_stack[255];


/* Data storage */
static int	b_2;	/* RETURN-CODE */
static cob_u8_t	b_17[40] __attribute__((aligned));	/* FILLER 1 */
static cob_u8_t	b_19[36] __attribute__((aligned));	/* WS-MATRIZ */
static cob_u8_t	b_21[3] __attribute__((aligned));	/* WS-VALOR */
static cob_u8_t	b_22[2] __attribute__((aligned));	/* WS-INDICE */
static cob_u8_t	b_23[2] __attribute__((aligned));	/* WS-CODIGO */
static cob_u8_t	b_24[40] __attribute__((aligned));	/* FILLER 2 */

/* End of local data storage */


/* Fields (local) */
static cob_field f_21	= {3, b_21, &a_2};	/* WS-VALOR */
static cob_field f_22	= {2, b_22, &a_3};	/* WS-INDICE */
static cob_field f_23	= {2, b_23, &a_3};	/* WS-CODIGO */

/* End of fields */

