/* Generated by           cobc 3.3-dev.0 */
/* Generated from         AMOST51.cbl */
/* Generated at           Mar 08 2026 10:43:02 */
/* GnuCOBOL build date    Mar 06 2024 10:59:48 */
/* GnuCOBOL package date  Mar 06 2024 09:58:52 UTC */
/* Compile command        C:\Program Files\GnuCOBOL\bin\cobc.exe -x -g AMOST51.cbl */

#include <string.h> /* for memcpy, memcmp and friends */
#define  COB_KEYWORD_INLINE __inline
#include <libcob.h>

#define  COB_SOURCE_FILE		"AMOST51.cbl"
#define  COB_PACKAGE_VERSION		"3.3-dev"
#define  COB_PATCH_LEVEL		0
#define  COB_MODULE_FORMATTED_DATE	"Mar 08 2026 10:43:02"
#define  COB_MODULE_DATE		20260308
#define  COB_MODULE_TIME		104302

/* Global variables */
#include "AMOST51.c.h"

/* Function prototypes */

static int		AMOST51 ();
static int		AMOST51_ (const int);
static void		AMOST51_module_init (cob_module *module);

/* Main function */
int
main (int argc, char **argv)
{
  cob_init (argc, argv);
  cob_stop_run (AMOST51 ());
}

/* Functions */

static void gc_module_so_init () __attribute__ ((constructor));
static void gc_module_so_init ()
{
  cob_check_version (COB_SOURCE_FILE, COB_PACKAGE_VERSION, COB_PATCH_LEVEL);
}

/* PROGRAM-ID 'AMOST51' */

/* ENTRY 'AMOST51' */

static int
AMOST51 ()
{
  return AMOST51_ (0);
}

static int
AMOST51_ (const int entry)
{
  /* Program local variables */
  #include "AMOST51.c.l.h"

  /* Start of function code */

  /* CANCEL callback */
  if (unlikely(entry < 0)) {
  	if (entry == -10)
  		goto P_dump;
  	if (entry == -20)
  		goto P_clear_decimal;
  	goto P_cancel;
  }

  /* Check initialized, check module allocated, */
  /* set global pointer, */
  /* push module stack, save call parameter count */
  if (cob_module_global_enter (&module, &cob_glob_ptr, 0, entry, 0))
  	return -1;

  /* Set address of module parameter list */
  module->cob_procedure_params = cob_procedure_params;

  /* Set frame stack pointer */
  frame_ptr = frame_stack;
  frame_ptr->perform_through = 0;
  frame_ptr->return_address_ptr = &&P_cgerror;
  frame_overflow = frame_ptr + 255 - 1;

  /* Initialize rest of program */
  if (unlikely(initialized == 0)) {
  	goto P_initialize;
  }
  P_ret_initialize:

  /* Increment module active */
  module->module_active++;

  /* Entry dispatch */
  goto l_2;

  /* PROCEDURE DIVISION */

  /* Line: 38        : Entry     AMOST51                 : AMOST51.cbl */
  l_2:;
#line 38 "AMOST51.cbl"
  ENTRY_AMOST51:	cob_nop ();
#line 105 "AMOST51.c"

  /* Line: 38        : Section   S000                    : AMOST51.cbl */
#line 38 "AMOST51.cbl"
  SECTION_S000:	cob_nop ();
#line 110 "AMOST51.c"

  /* Line: 39        : Paragraph P001-INICIO             : AMOST51.cbl */
#line 39 "AMOST51.cbl"
  PARAGRAPH_P001__INICIO_l_4:	cob_nop ();
#line 115 "AMOST51.c"

  /* Line: 40        : MOVE               : AMOST51.cbl */
#line 40 "AMOST51.cbl"
  cob_nop ();
#line 120 "AMOST51.c"
  memcpy (b_21, "011", 3);

  /* Line: 41        : PERFORM            : AMOST51.cbl */
#line 41 "AMOST51.cbl"
  cob_nop ();
#line 126 "AMOST51.c"
  memcpy (b_22, "01", 2);
  for (;;)
  {
    /* Line: 42        : UNTIL              : AMOST51.cbl */
#line 42 "AMOST51.cbl"
    cob_nop ();
#line 133 "AMOST51.c"
    if (((int)cob_cmp_numdisp (b_22, 2, COB_S64_C(12), 0) > 0))
      break;

    /* Line: 43        : DISPLAY            : AMOST51.cbl */
#line 43 "AMOST51.cbl"
    cob_nop ();
#line 140 "AMOST51.c"
    cob_display (0, 1, 1, &c_1);

    /* Line: 44        : MOVE               : AMOST51.cbl */
#line 44 "AMOST51.cbl"
    cob_nop ();
#line 146 "AMOST51.c"
    memcpy (b_19 + 3LL * ((cob_s64_t)(cob_get_numdisp (b_22, 2)) - 1), b_21, 3);

    /* Line: 45        : DISPLAY            : AMOST51.cbl */
#line 45 "AMOST51.cbl"
    cob_nop ();
#line 152 "AMOST51.c"
    cob_display (0, 1, 4, &c_2, COB_SET_FLD (f0, 3, b_19 + 3LL * ((cob_s64_t)(cob_get_numdisp (b_22, 2)) - 1), &a_2), &c_3, &f_22);

    /* Line: 47        : ADD                : AMOST51.cbl */
#line 47 "AMOST51.cbl"
    cob_nop ();
#line 158 "AMOST51.c"
    cob_add_int (&f_21, 11, 0);
    /* Line: 41        : VARYING            : AMOST51.cbl */
#line 41 "AMOST51.cbl"
    cob_nop ();
#line 163 "AMOST51.c"
    cob_add_int (&f_22, 1, 0);
  }

  /* Line: 50        : DISPLAY            : AMOST51.cbl */
#line 50 "AMOST51.cbl"
  cob_nop ();
#line 170 "AMOST51.c"
  cob_display (0, 1, 1, &c_1);

  /* Line: 51        : DISPLAY            : AMOST51.cbl */
#line 51 "AMOST51.cbl"
  cob_nop ();
#line 176 "AMOST51.c"
  cob_display (0, 1, 1, &c_4);

  /* Line: 52        : ACCEPT             : AMOST51.cbl */
#line 52 "AMOST51.cbl"
  cob_nop ();
#line 182 "AMOST51.c"
  cob_accept (&f_23);

  /* Line: 54        : DISPLAY            : AMOST51.cbl */
#line 54 "AMOST51.cbl"
  cob_nop ();
#line 188 "AMOST51.c"
  cob_display (0, 1, 2, &c_5, COB_SET_FLD (f0, 3, b_19 + 3LL * ((cob_s64_t)(cob_get_numdisp (b_23, 2)) - 1), &a_2));

  /* Line: 56        : Paragraph P001-EXIT               : AMOST51.cbl */
#line 56 "AMOST51.cbl"
  PARAGRAPH_P001__EXIT_l_5:	cob_nop ();
#line 194 "AMOST51.c"

  /* Line: 57        : EXIT               : AMOST51.cbl */
#line 57 "AMOST51.cbl"
  cob_nop ();
#line 199 "AMOST51.c"

  /* Line: 59        : Section   S900                    : AMOST51.cbl */
#line 59 "AMOST51.cbl"
  SECTION_S900:	cob_nop ();
#line 204 "AMOST51.c"

  /* Line: 60        : Paragraph P901-TERMINO            : AMOST51.cbl */
#line 60 "AMOST51.cbl"
  PARAGRAPH_P901__TERMINO_l_7:	cob_nop ();
#line 209 "AMOST51.c"

  /* Line: 61        : STOP RUN           : AMOST51.cbl */
#line 61 "AMOST51.cbl"
  cob_nop ();
#line 214 "AMOST51.c"
  cob_stop_run (b_2);

  /* Line: 63        : Paragraph P901-EXIT               : AMOST51.cbl */
#line 63 "AMOST51.cbl"
  PARAGRAPH_P901__EXIT_l_8:	cob_nop ();
#line 220 "AMOST51.c"

  /* Line: 64        : EXIT               : AMOST51.cbl */
#line 64 "AMOST51.cbl"
  cob_nop ();
#line 225 "AMOST51.c"

  /* Program exit */

  exit_program:

  /* Decrement module active count */
  if (module->module_active) {
  	module->module_active--;
  }

  /* Pop module stack */
  cob_module_leave (module);

  /* Program return */
  return b_2;
  P_cgerror:
  	cob_fatal_error (COB_FERROR_CODEGEN);


  /* Program initialization */
  P_initialize:

  cob_module_path = cob_glob_ptr->cob_main_argv0;

  AMOST51_module_init (module);

  module->collating_sequence = NULL;
  module->crt_status = NULL;
  module->cursor_pos = NULL;
  module->xml_code = NULL;
  module->xml_event = NULL;
  module->xml_information = NULL;
  module->xml_namespace = NULL;
  module->xml_namespace_prefix = NULL;
  module->xml_nnamespace = NULL;
  module->xml_nnamespace_prefix = NULL;
  module->xml_ntext = NULL;
  module->xml_text = NULL;
  module->json_code = NULL;
  module->json_status = NULL;

  /* Initialize cancel callback */
  cob_set_cancel (module);

  /* Initialize WORKING-STORAGE */
  /* initialize field RETURN-CODE */
  b_2 = 0;

  /* initialize field FILLER 1 */
#line 20 "AMOST51.cbl"
  cob_nop ();
#line 277 "AMOST51.c"
  memset (b_17, (unsigned char)' ', 40);

  /* initialize field WS-MATRIZ */
#line 25 "AMOST51.cbl"
  cob_nop ();
#line 283 "AMOST51.c"
  memset (b_19, (unsigned char)'0', 36);

  /* initialize field WS-VALOR */
#line 28 "AMOST51.cbl"
  cob_nop ();
#line 289 "AMOST51.c"
  memset (b_21, 48, 3);

  /* initialize field WS-INDICE */
#line 29 "AMOST51.cbl"
  cob_nop ();
#line 295 "AMOST51.c"
  memset (b_22, 48, 2);

  /* initialize field WS-CODIGO */
#line 30 "AMOST51.cbl"
  cob_nop ();
#line 301 "AMOST51.c"
  memset (b_23, 48, 2);

  /* initialize field FILLER 2 */
#line 32 "AMOST51.cbl"
  cob_nop ();
#line 307 "AMOST51.c"
  memset (b_24, (unsigned char)' ', 40);


  if (0 == 1) goto P_cgerror;
  initialized = 1;
  goto P_ret_initialize;

  P_dump:
    return 0;


  /* CANCEL callback handling */
  P_cancel:

  if (!initialized)
  	return 0;
  if (module && module->module_active)
  	cob_fatal_error (COB_FERROR_CANCEL);

  initialized = 0;

  P_clear_decimal:
  return 0;

}

/* End PROGRAM-ID 'AMOST51' */

/* Initialize module structure for AMOST51 */
static void AMOST51_module_init (cob_module *module)
{
  module->module_name = "AMOST51";
  module->module_formatted_date = COB_MODULE_FORMATTED_DATE;
  module->module_source = COB_SOURCE_FILE;
  module->gc_version = COB_PACKAGE_VERSION;
  module->module_entry.funcptr = (void *(*)())AMOST51;
  module->module_cancel.funcptr = (void *(*)())AMOST51_;
  module->module_ref_count = NULL;
  module->module_path = &cob_module_path;
  module->module_active = 0;
  module->module_date = COB_MODULE_DATE;
  module->module_time = COB_MODULE_TIME;
  module->module_type = 0;
  module->module_param_cnt = 0;
  module->ebcdic_sign = 0;
  module->decimal_point = ',';
  module->currency_symbol = '$';
  module->numeric_separator = '.';
  module->flag_filename_mapping = 1;
  module->flag_binary_truncate = 1;
  module->flag_pretty_display = 1;
  module->flag_host_sign = 0;
  module->flag_no_phys_canc = 1;
  module->flag_main = 1;
  module->flag_fold_call = 0;
  module->flag_exit_program = 0;
  module->flag_debug_trace = 0;
  module->flag_dump_ready = 0;
  module->xml_mode = 1;
  module->module_stmt = 0;
  module->module_sources = NULL;
}

/* End functions */

