/* Generated by           cobc 3.3-dev.0 */
/* Generated from         EVALUATE.cbl */
/* Generated at           Mar 08 2026 10:56:38 */
/* GnuCOBOL build date    Mar 06 2024 10:59:48 */
/* GnuCOBOL package date  Mar 06 2024 09:58:52 UTC */
/* Compile command        C:\Program Files\GnuCOBOL\bin\cobc.exe -x -g EVALUATE.cbl */


/* Module path */
static const char		*cob_module_path = NULL;

/* Number of call parameters */
static int		cob_call_params = 0;

/* Attributes */

static const cob_field_attr a_1 =	{0x21,   0,   0, 0x1000, NULL};
static const cob_field_attr a_2 =	{0x10,   2,   0, 0x0000, NULL};
static const cob_field_attr a_3 =	{0x21,   0,   0, 0x0000, NULL};


/* Constants */
static const cob_field c_1	= {32, (cob_u8_ptr)"DIGITE O NUMERO DO MES (01 A 12)", &a_1};
static const cob_field c_2	= {7, (cob_u8_ptr)"JANEIRO", &a_1};
static const cob_field c_3	= {9, (cob_u8_ptr)"FEVEREIRO", &a_1};
static const cob_field c_4	= {5, (cob_u8_ptr)"MARCO", &a_1};
static const cob_field c_5	= {5, (cob_u8_ptr)"ABRIL", &a_1};
static const cob_field c_6	= {4, (cob_u8_ptr)"MAIO", &a_1};
static const cob_field c_7	= {5, (cob_u8_ptr)"JUNHO", &a_1};
static const cob_field c_8	= {5, (cob_u8_ptr)"JULHO", &a_1};
static const cob_field c_9	= {6, (cob_u8_ptr)"AGOSTO", &a_1};
static const cob_field c_10	= {8, (cob_u8_ptr)"SETEMBRO", &a_1};
static const cob_field c_11	= {7, (cob_u8_ptr)"OUTUBRO", &a_1};
static const cob_field c_12	= {8, (cob_u8_ptr)"NOVEMBRO", &a_1};
static const cob_field c_13	= {8, (cob_u8_ptr)"DEZEMBRO", &a_1};
static const cob_field c_14	= {13, (cob_u8_ptr)"MES INVALIDO!", &a_1};
static const cob_field c_15	= {26, (cob_u8_ptr)"DESEJA AVALIAR OUTRO MES\? ", &a_1};
static const cob_field c_16	= {25, (cob_u8_ptr)"DIGITE (S) SIM OU (N) NAO", &a_1};


#define cob_nop	if (!module) cob_nop

