/* Generated by           cobc 3.3-dev.0 */
/* Generated from         EVALUATE.cbl */
/* Generated at           Mar 08 2026 10:56:38 */
/* GnuCOBOL build date    Mar 06 2024 10:59:48 */
/* GnuCOBOL package date  Mar 06 2024 09:58:52 UTC */
/* Compile command        C:\Program Files\GnuCOBOL\bin\cobc.exe -x -g EVALUATE.cbl */

#include <string.h> /* for memcpy, memcmp and friends */
#define  COB_KEYWORD_INLINE __inline
#include <libcob.h>

#define  COB_SOURCE_FILE		"EVALUATE.cbl"
#define  COB_PACKAGE_VERSION		"3.3-dev"
#define  COB_PATCH_LEVEL		0
#define  COB_MODULE_FORMATTED_DATE	"Mar 08 2026 10:56:38"
#define  COB_MODULE_DATE		20260308
#define  COB_MODULE_TIME		105638

/* Global variables */
#include "EVALUATE.c.h"

/* Function prototypes */

static int		PGM__EVALUATE ();
static int		PGM__EVALUATE_ (const int);
static void		PGM__EVALUATE_module_init (cob_module *module);

/* Main function */
int
main (int argc, char **argv)
{
  cob_init (argc, argv);
  cob_stop_run (PGM__EVALUATE ());
}

/* Functions */

static void gc_module_so_init () __attribute__ ((constructor));
static void gc_module_so_init ()
{
  cob_check_version (COB_SOURCE_FILE, COB_PACKAGE_VERSION, COB_PATCH_LEVEL);
}

/* PROGRAM-ID 'PGM-EVALUATE' */

/* ENTRY 'PGM__EVALUATE' */

static int
PGM__EVALUATE ()
{
  return PGM__EVALUATE_ (0);
}

static int
PGM__EVALUATE_ (const int entry)
{
  /* Program local variables */
  #include "EVALUATE.c.l.h"

  /* Start of function code */

  /* CANCEL callback */
  if (unlikely(entry < 0)) {
  	if (entry == -10)
  		goto P_dump;
  	if (entry == -20)
  		goto P_clear_decimal;
  	goto P_cancel;
  }

  /* Check initialized, check module allocated, */
  /* set global pointer, */
  /* push module stack, save call parameter count */
  if (cob_module_global_enter (&module, &cob_glob_ptr, 0, entry, 0))
  	return -1;

  /* Set address of module parameter list */
  module->cob_procedure_params = cob_procedure_params;

  /* Set frame stack pointer */
  frame_ptr = frame_stack;
  frame_ptr->perform_through = 0;
  frame_ptr->return_address_ptr = &&P_cgerror;
  frame_overflow = frame_ptr + 255 - 1;

  /* Initialize rest of program */
  if (unlikely(initialized == 0)) {
  	goto P_initialize;
  }
  P_ret_initialize:

  /* Increment module active */
  module->module_active++;

  /* Entry dispatch */
  goto l_2;

  /* PROCEDURE DIVISION */

  /* Line: 15        : Entry     PGM-EVALUATE            : EVALUATE.cbl */
  l_2:;
#line 15 "EVALUATE.cbl"
  ENTRY_PGM__EVALUATE:	cob_nop ();
#line 105 "EVALUATE.c"

  /* Line: 15        : Section   S000-INI                : EVALUATE.cbl */
#line 15 "EVALUATE.cbl"
  SECTION_S000__INI:	cob_nop ();
#line 110 "EVALUATE.c"

  /* Line: 16        : Paragraph P001-INICIO             : EVALUATE.cbl */
  l_4:;
#line 16 "EVALUATE.cbl"
  PARAGRAPH_P001__INICIO_l_4:	cob_nop ();
#line 116 "EVALUATE.c"

  /* Line: 17        : DISPLAY            : EVALUATE.cbl */
#line 17 "EVALUATE.cbl"
  cob_nop ();
#line 121 "EVALUATE.c"
  cob_display (0, 1, 1, &c_1);

  /* Line: 18        : ACCEPT             : EVALUATE.cbl */
#line 18 "EVALUATE.cbl"
  cob_nop ();
#line 127 "EVALUATE.c"
  cob_accept (&f_18);

  /* Line: 20        : EVALUATE           : EVALUATE.cbl */
#line 20 "EVALUATE.cbl"
  cob_nop ();
#line 133 "EVALUATE.c"

  /* Line: 21        : WHEN               : EVALUATE.cbl */
#line 21 "EVALUATE.cbl"
  cob_nop ();
#line 138 "EVALUATE.c"

  if (((int)cob_cmp_numdisp (b_17, 2, COB_S64_C(1), 0) == 0))
  {

    /* Line: 21        : DISPLAY            : EVALUATE.cbl */
#line 21 "EVALUATE.cbl"
    cob_nop ();
#line 146 "EVALUATE.c"
    cob_display (0, 1, 1, &c_2);
    goto l_5;
  }

  /* Line: 22        : WHEN               : EVALUATE.cbl */
#line 22 "EVALUATE.cbl"
  cob_nop ();
#line 154 "EVALUATE.c"

  if (((int)cob_cmp_numdisp (b_17, 2, COB_S64_C(2), 0) == 0))
  {

    /* Line: 22        : DISPLAY            : EVALUATE.cbl */
#line 22 "EVALUATE.cbl"
    cob_nop ();
#line 162 "EVALUATE.c"
    cob_display (0, 1, 1, &c_3);
    goto l_5;
  }

  /* Line: 23        : WHEN               : EVALUATE.cbl */
#line 23 "EVALUATE.cbl"
  cob_nop ();
#line 170 "EVALUATE.c"

  if (((int)cob_cmp_numdisp (b_17, 2, COB_S64_C(3), 0) == 0))
  {

    /* Line: 23        : DISPLAY            : EVALUATE.cbl */
#line 23 "EVALUATE.cbl"
    cob_nop ();
#line 178 "EVALUATE.c"
    cob_display (0, 1, 1, &c_4);
    goto l_5;
  }

  /* Line: 24        : WHEN               : EVALUATE.cbl */
#line 24 "EVALUATE.cbl"
  cob_nop ();
#line 186 "EVALUATE.c"

  if (((int)cob_cmp_numdisp (b_17, 2, COB_S64_C(4), 0) == 0))
  {

    /* Line: 24        : DISPLAY            : EVALUATE.cbl */
#line 24 "EVALUATE.cbl"
    cob_nop ();
#line 194 "EVALUATE.c"
    cob_display (0, 1, 1, &c_5);
    goto l_5;
  }

  /* Line: 25        : WHEN               : EVALUATE.cbl */
#line 25 "EVALUATE.cbl"
  cob_nop ();
#line 202 "EVALUATE.c"

  if (((int)cob_cmp_numdisp (b_17, 2, COB_S64_C(5), 0) == 0))
  {

    /* Line: 25        : DISPLAY            : EVALUATE.cbl */
#line 25 "EVALUATE.cbl"
    cob_nop ();
#line 210 "EVALUATE.c"
    cob_display (0, 1, 1, &c_6);
    goto l_5;
  }

  /* Line: 26        : WHEN               : EVALUATE.cbl */
#line 26 "EVALUATE.cbl"
  cob_nop ();
#line 218 "EVALUATE.c"

  if (((int)cob_cmp_numdisp (b_17, 2, COB_S64_C(6), 0) == 0))
  {

    /* Line: 26        : DISPLAY            : EVALUATE.cbl */
#line 26 "EVALUATE.cbl"
    cob_nop ();
#line 226 "EVALUATE.c"
    cob_display (0, 1, 1, &c_7);
    goto l_5;
  }

  /* Line: 27        : WHEN               : EVALUATE.cbl */
#line 27 "EVALUATE.cbl"
  cob_nop ();
#line 234 "EVALUATE.c"

  if (((int)cob_cmp_numdisp (b_17, 2, COB_S64_C(7), 0) == 0))
  {

    /* Line: 27        : DISPLAY            : EVALUATE.cbl */
#line 27 "EVALUATE.cbl"
    cob_nop ();
#line 242 "EVALUATE.c"
    cob_display (0, 1, 1, &c_8);
    goto l_5;
  }

  /* Line: 28        : WHEN               : EVALUATE.cbl */
#line 28 "EVALUATE.cbl"
  cob_nop ();
#line 250 "EVALUATE.c"

  if (((int)cob_cmp_numdisp (b_17, 2, COB_S64_C(8), 0) == 0))
  {

    /* Line: 28        : DISPLAY            : EVALUATE.cbl */
#line 28 "EVALUATE.cbl"
    cob_nop ();
#line 258 "EVALUATE.c"
    cob_display (0, 1, 1, &c_9);
    goto l_5;
  }

  /* Line: 29        : WHEN               : EVALUATE.cbl */
#line 29 "EVALUATE.cbl"
  cob_nop ();
#line 266 "EVALUATE.c"

  if (((int)cob_cmp_numdisp (b_17, 2, COB_S64_C(9), 0) == 0))
  {

    /* Line: 29        : DISPLAY            : EVALUATE.cbl */
#line 29 "EVALUATE.cbl"
    cob_nop ();
#line 274 "EVALUATE.c"
    cob_display (0, 1, 1, &c_10);
    goto l_5;
  }

  /* Line: 30        : WHEN               : EVALUATE.cbl */
#line 30 "EVALUATE.cbl"
  cob_nop ();
#line 282 "EVALUATE.c"

  if (((int)cob_cmp_numdisp (b_17, 2, COB_S64_C(10), 0) == 0))
  {

    /* Line: 30        : DISPLAY            : EVALUATE.cbl */
#line 30 "EVALUATE.cbl"
    cob_nop ();
#line 290 "EVALUATE.c"
    cob_display (0, 1, 1, &c_11);
    goto l_5;
  }

  /* Line: 31        : WHEN               : EVALUATE.cbl */
#line 31 "EVALUATE.cbl"
  cob_nop ();
#line 298 "EVALUATE.c"

  if (((int)cob_cmp_numdisp (b_17, 2, COB_S64_C(11), 0) == 0))
  {

    /* Line: 31        : DISPLAY            : EVALUATE.cbl */
#line 31 "EVALUATE.cbl"
    cob_nop ();
#line 306 "EVALUATE.c"
    cob_display (0, 1, 1, &c_12);
    goto l_5;
  }

  /* Line: 32        : WHEN               : EVALUATE.cbl */
#line 32 "EVALUATE.cbl"
  cob_nop ();
#line 314 "EVALUATE.c"

  if (((int)cob_cmp_numdisp (b_17, 2, COB_S64_C(12), 0) == 0))
  {

    /* Line: 32        : DISPLAY            : EVALUATE.cbl */
#line 32 "EVALUATE.cbl"
    cob_nop ();
#line 322 "EVALUATE.c"
    cob_display (0, 1, 1, &c_13);
    goto l_5;
  }

  /* WHEN OTHER */

  /* Line: 33        : DISPLAY            : EVALUATE.cbl */
#line 33 "EVALUATE.cbl"
  cob_nop ();
#line 332 "EVALUATE.c"
  cob_display (0, 1, 1, &c_14);

  /* End EVALUATE */
  l_5:;

  /* Line: 36        : DISPLAY            : EVALUATE.cbl */
#line 36 "EVALUATE.cbl"
  cob_nop ();
#line 341 "EVALUATE.c"
  cob_display (0, 1, 1, &c_15);

  /* Line: 37        : DISPLAY            : EVALUATE.cbl */
#line 37 "EVALUATE.cbl"
  cob_nop ();
#line 347 "EVALUATE.c"
  cob_display (0, 1, 1, &c_16);

  /* Line: 38        : ACCEPT             : EVALUATE.cbl */
#line 38 "EVALUATE.cbl"
  cob_nop ();
#line 353 "EVALUATE.c"
  cob_accept (&f_19);

  /* Line: 40        : IF                 : EVALUATE.cbl */
#line 40 "EVALUATE.cbl"
  cob_nop ();
#line 359 "EVALUATE.c"
  if (((int)(int)(*(b_17 + 2) - (unsigned char)'S') == 0))
  {

    /* Line: 41        : PERFORM            : EVALUATE.cbl */
#line 41 "EVALUATE.cbl"
    cob_nop ();
#line 366 "EVALUATE.c"
    /* PERFORM P001-INICIO */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 4;
    frame_ptr->return_address_ptr = &&l_10;
    goto l_4;
    l_10:
    frame_ptr--;
  }
  else
  {
    /* ELSE */

    /* Line: 43        : CONTINUE           : EVALUATE.cbl */
#line 43 "EVALUATE.cbl"
    cob_nop ();
#line 384 "EVALUATE.c"
    ;
  }

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 4)
    goto *frame_ptr->return_address_ptr;

  /* Line: 46        : Paragraph P001-EXIT               : EVALUATE.cbl */
#line 46 "EVALUATE.cbl"
  PARAGRAPH_P001__EXIT_l_6:	cob_nop ();
#line 395 "EVALUATE.c"

  /* Line: 47        : EXIT               : EVALUATE.cbl */
#line 47 "EVALUATE.cbl"
  cob_nop ();
#line 400 "EVALUATE.c"

  /* Line: 49        : Section   S900-FIM                : EVALUATE.cbl */
#line 49 "EVALUATE.cbl"
  SECTION_S900__FIM:	cob_nop ();
#line 405 "EVALUATE.c"

  /* Line: 50        : Paragraph P999-FIM                : EVALUATE.cbl */
#line 50 "EVALUATE.cbl"
  PARAGRAPH_P999__FIM_l_8:	cob_nop ();
#line 410 "EVALUATE.c"

  /* Line: 51        : STOP RUN           : EVALUATE.cbl */
#line 51 "EVALUATE.cbl"
  cob_nop ();
#line 415 "EVALUATE.c"
  cob_stop_run (b_2);

  /* Line: 52        : Paragraph P999-EXIT               : EVALUATE.cbl */
#line 52 "EVALUATE.cbl"
  PARAGRAPH_P999__EXIT_l_9:	cob_nop ();
#line 421 "EVALUATE.c"

  /* Line: 53        : EXIT               : EVALUATE.cbl */
#line 53 "EVALUATE.cbl"
  cob_nop ();
#line 426 "EVALUATE.c"

  /* Program exit */

  exit_program:

  /* Decrement module active count */
  if (module->module_active) {
  	module->module_active--;
  }

  /* Pop module stack */
  cob_module_leave (module);

  /* Program return */
  return b_2;
  P_cgerror:
  	cob_fatal_error (COB_FERROR_CODEGEN);


  /* Program initialization */
  P_initialize:

  cob_module_path = cob_glob_ptr->cob_main_argv0;

  PGM__EVALUATE_module_init (module);

  module->collating_sequence = NULL;
  module->crt_status = NULL;
  module->cursor_pos = NULL;
  module->xml_code = NULL;
  module->xml_event = NULL;
  module->xml_information = NULL;
  module->xml_namespace = NULL;
  module->xml_namespace_prefix = NULL;
  module->xml_nnamespace = NULL;
  module->xml_nnamespace_prefix = NULL;
  module->xml_ntext = NULL;
  module->xml_text = NULL;
  module->json_code = NULL;
  module->json_status = NULL;

  /* Initialize cancel callback */
  cob_set_cancel (module);

  /* Initialize WORKING-STORAGE */
  /* initialize field RETURN-CODE */
  b_2 = 0;

  /* initialize field WS-MES */
#line 12 "EVALUATE.cbl"
  cob_nop ();
#line 478 "EVALUATE.c"
  memset (b_17, (unsigned char)'0', 2);
  /* initialize field WS-STATUS */
#line 13 "EVALUATE.cbl"
  cob_nop ();
#line 483 "EVALUATE.c"
  *(cob_u8_ptr)(b_17 + 2) = (unsigned char)' ';


  if (0 == 1) goto P_cgerror;
  initialized = 1;
  goto P_ret_initialize;

  P_dump:
    return 0;


  /* CANCEL callback handling */
  P_cancel:

  if (!initialized)
  	return 0;
  if (module && module->module_active)
  	cob_fatal_error (COB_FERROR_CANCEL);

  initialized = 0;

  P_clear_decimal:
  return 0;

}

/* End PROGRAM-ID 'PGM-EVALUATE' */

/* Initialize module structure for PGM-EVALUATE */
static void PGM__EVALUATE_module_init (cob_module *module)
{
  module->module_name = "PGM-EVALUATE";
  module->module_formatted_date = COB_MODULE_FORMATTED_DATE;
  module->module_source = COB_SOURCE_FILE;
  module->gc_version = COB_PACKAGE_VERSION;
  module->module_entry.funcptr = (void *(*)())PGM__EVALUATE;
  module->module_cancel.funcptr = (void *(*)())PGM__EVALUATE_;
  module->module_ref_count = NULL;
  module->module_path = &cob_module_path;
  module->module_active = 0;
  module->module_date = COB_MODULE_DATE;
  module->module_time = COB_MODULE_TIME;
  module->module_type = 0;
  module->module_param_cnt = 0;
  module->ebcdic_sign = 0;
  module->decimal_point = '.';
  module->currency_symbol = '$';
  module->numeric_separator = ',';
  module->flag_filename_mapping = 1;
  module->flag_binary_truncate = 1;
  module->flag_pretty_display = 1;
  module->flag_host_sign = 0;
  module->flag_no_phys_canc = 1;
  module->flag_main = 1;
  module->flag_fold_call = 0;
  module->flag_exit_program = 0;
  module->flag_debug_trace = 0;
  module->flag_dump_ready = 0;
  module->xml_mode = 1;
  module->module_stmt = 0;
  module->module_sources = NULL;
}

/* End functions */

