/* Generated by           cobc 3.3-dev.0 */
/* Generated from         EXEMPL01.cbl */
/* Generated at           Mar 08 2026 11:07:00 */
/* GnuCOBOL build date    Mar 06 2024 10:59:48 */
/* GnuCOBOL package date  Mar 06 2024 09:58:52 UTC */
/* Compile command        C:\Program Files\GnuCOBOL\bin\cobc.exe -x -g EXEMPL01.cbl */


/* Module path */
static const char		*cob_module_path = NULL;

/* Number of call parameters */
static int		cob_call_params = 0;

/* Attributes */

static const cob_field_attr a_1 =	{0x10,   8,   0, 0x0000, NULL};
static const cob_field_attr a_2 =	{0x21,   0,   0, 0x0000, NULL};
static const cob_field_attr a_3 =	{0x10,   2,   0, 0x0000, NULL};
static const cob_field_attr a_4 =	{0x10,   4,   0, 0x0000, NULL};
static const cob_field_attr a_5 =	{0x10,   5,   0, 0x0000, NULL};
static const cob_field_attr a_6 =	{0x21,   0,   0, 0x1000, NULL};
static const cob_field_attr a_7 =	{0x01,   0,   0, 0x0000, NULL};


/* Constants */
static const cob_field c_1	= {3, (cob_u8_ptr)" - ", &a_6};
static const cob_field c_2	= {46, (cob_u8_ptr)"==============================================", &a_6};
static const cob_field c_3	= {46, (cob_u8_ptr)"     MENSAGEM DO PROCESSAMENTO DO PROGRAMA    ", &a_6};
static const cob_field c_4	= {12, (cob_u8_ptr)"MENSAGEM  = ", &a_6};
static const cob_field c_5	= {12, (cob_u8_ptr)"CODIGO    = ", &a_6};
static const cob_field c_6	= {24, (cob_u8_ptr)"INICIO  PROCESSAMENTO = ", &a_6};
static const cob_field c_7	= {1, (cob_u8_ptr)"-", &a_6};
static const cob_field c_8	= {24, (cob_u8_ptr)"TERMINO PROCESSAMENTO = ", &a_6};
static const cob_field c_9	= {33, (cob_u8_ptr)"              TERMINO DO PROGRAMA", &a_6};
static const cob_field c_10	= {27, (cob_u8_ptr)"REGISTROS STUDENT LIDOS  = ", &a_6};
static const cob_field c_11	= {23, (cob_u8_ptr)"C:\\Arquivos\\STUDENT.txt", &a_6};


#define cob_nop	if (!module) cob_nop

