/* Generated by           cobc 3.3-dev.0 */
/* Generated from         EXEMPL01.cbl */
/* Generated at           Mar 08 2026 11:07:00 */
/* GnuCOBOL build date    Mar 06 2024 10:59:48 */
/* GnuCOBOL package date  Mar 06 2024 09:58:52 UTC */
/* Compile command        C:\Program Files\GnuCOBOL\bin\cobc.exe -x -g EXEMPL01.cbl */

/* Program local variables for 'PGMARQ02' */

/* Module initialization indicator */
static unsigned int	initialized = 0;

/* Module structure pointer */
static cob_module	*module = NULL;

/* Global variable pointer */
cob_global		*cob_glob_ptr;


/* File STUDENT */
static cob_file		*h_STUDENT = NULL;
static unsigned char	h_STUDENT_status[4];

/* LINKAGE SECTION (Items not referenced by USING clause) */
static unsigned char	*b_9 = NULL;  /* XML-NAMESPACE */
static unsigned char	*b_10 = NULL;  /* XML-NAMESPACE-PREFIX */
static unsigned char	*b_11 = NULL;  /* XML-NNAMESPACE */
static unsigned char	*b_12 = NULL;  /* XML-NNAMESPACE-PREFIX */
static unsigned char	*b_13 = NULL;  /* XML-NTEXT */
static unsigned char	*b_14 = NULL;  /* XML-TEXT */


/* Local cob_field items */
cob_field		f0;


/* Call parameters */
cob_field		*cob_procedure_params[1];

/* Perform frame stack */
struct cob_frame	*frame_overflow;
struct cob_frame	*frame_ptr;
struct cob_frame	frame_stack[255];


/* Data storage */
static int	b_2;	/* RETURN-CODE */
static cob_u8_t	b_20[30] __attribute__((aligned));	/* STUDENT Record */
static cob_u8_t	b_21[30] __attribute__((aligned));	/* WS-DADOS */
static cob_u8_t	b_25[2] __attribute__((aligned));	/* WS-FS-STU */
static cob_u8_t	b_26[35] __attribute__((aligned));	/* WS-MSG-A */
static cob_u8_t	b_27[2] __attribute__((aligned));	/* WS-MSG-B */
static cob_u8_t	b_28[8] __attribute__((aligned));	/* WS-DATA */
static cob_u8_t	b_29[10] __attribute__((aligned));	/* WS-DATA-E */
static cob_u8_t	b_35[8] __attribute__((aligned));	/* WS-HORA */
static cob_u8_t	b_36[8] __attribute__((aligned));	/* WS-HORA-I */
static cob_u8_t	b_42[8] __attribute__((aligned));	/* WS-HORA-F */
static cob_u8_t	b_48[2] __attribute__((aligned));	/* WS-LER-STU */
static cob_u8_t	b_49[1] __attribute__((aligned));	/* WS-EOF */

/* End of local data storage */


/* Fields (local) */
static cob_field f_20	= {30, b_20, &a_2};	/* STUDENT Record */
static cob_field f_23	= {5, b_21, &a_5};	/* WS-COD-STUDENT */
static cob_field f_24	= {25, b_21 + 5, &a_2};	/* WS-NOM-STUDENT */
static cob_field f_25	= {2, b_25, &a_3};	/* WS-FS-STU */
static cob_field f_26	= {35, b_26, &a_2};	/* WS-MSG-A */
static cob_field f_27	= {2, b_27, &a_3};	/* WS-MSG-B */
static cob_field f_28	= {8, b_28, &a_1};	/* WS-DATA */
static cob_field f_29	= {10, b_29, &a_7};	/* WS-DATA-E */
static cob_field f_30	= {2, b_29, &a_3};	/* WS-DD */
static cob_field f_32	= {2, b_29 + 3, &a_3};	/* WS-MM */
static cob_field f_34	= {4, b_29 + 6, &a_4};	/* WS-AA */
static cob_field f_35	= {8, b_35, &a_1};	/* WS-HORA */
static cob_field f_36	= {8, b_36, &a_7};	/* WS-HORA-I */
static cob_field f_37	= {2, b_36, &a_3};	/* WS-HR-I */
static cob_field f_39	= {2, b_36 + 3, &a_3};	/* WS-MI-I */
static cob_field f_41	= {2, b_36 + 6, &a_3};	/* WS-SE-I */
static cob_field f_42	= {8, b_42, &a_7};	/* WS-HORA-F */
static cob_field f_43	= {2, b_42, &a_3};	/* WS-HR-F */
static cob_field f_45	= {2, b_42 + 3, &a_3};	/* WS-MI-F */
static cob_field f_47	= {2, b_42 + 6, &a_3};	/* WS-SE-F */
static cob_field f_48	= {2, b_48, &a_3};	/* WS-LER-STU */

/* End of fields */

