/* Generated by           cobc 3.3-dev.0 */
/* Generated from         EXEMPL01.cbl */
/* Generated at           Mar 08 2026 11:07:00 */
/* GnuCOBOL build date    Mar 06 2024 10:59:48 */
/* GnuCOBOL package date  Mar 06 2024 09:58:52 UTC */
/* Compile command        C:\Program Files\GnuCOBOL\bin\cobc.exe -x -g EXEMPL01.cbl */

#include <string.h> /* for memcpy, memcmp and friends */
#define  COB_KEYWORD_INLINE __inline
#include <libcob.h>

#define  COB_SOURCE_FILE		"EXEMPL01.cbl"
#define  COB_PACKAGE_VERSION		"3.3-dev"
#define  COB_PATCH_LEVEL		0
#define  COB_MODULE_FORMATTED_DATE	"Mar 08 2026 11:07:00"
#define  COB_MODULE_DATE		20260308
#define  COB_MODULE_TIME		110700

/* Global variables */
#include "EXEMPL01.c.h"

/* Function prototypes */

static int		PGMARQ02 ();
static int		PGMARQ02_ (const int);
static void		PGMARQ02_module_init (cob_module *module);

/* Main function */
int
main (int argc, char **argv)
{
  cob_init (argc, argv);
  cob_stop_run (PGMARQ02 ());
}

/* Functions */

static void gc_module_so_init () __attribute__ ((constructor));
static void gc_module_so_init ()
{
  cob_check_version (COB_SOURCE_FILE, COB_PACKAGE_VERSION, COB_PATCH_LEVEL);
}

/* PROGRAM-ID 'PGMARQ02' */

/* ENTRY 'PGMARQ02' */

static int
PGMARQ02 ()
{
  return PGMARQ02_ (0);
}

static int
PGMARQ02_ (const int entry)
{
  /* Program local variables */
  #include "EXEMPL01.c.l.h"

  /* Start of function code */

  /* CANCEL callback */
  if (unlikely(entry < 0)) {
  	if (entry == -10)
  		goto P_dump;
  	if (entry == -20)
  		goto P_clear_decimal;
  	goto P_cancel;
  }

  /* Check initialized, check module allocated, */
  /* set global pointer, */
  /* push module stack, save call parameter count */
  if (cob_module_global_enter (&module, &cob_glob_ptr, 0, entry, 0))
  	return -1;

  /* Set address of module parameter list */
  module->cob_procedure_params = cob_procedure_params;

  /* Set frame stack pointer */
  frame_ptr = frame_stack;
  frame_ptr->perform_through = 0;
  frame_ptr->return_address_ptr = &&P_cgerror;
  frame_overflow = frame_ptr + 255 - 1;

  /* Initialize rest of program */
  if (unlikely(initialized == 0)) {
  	goto P_initialize;
  }
  P_ret_initialize:

  /* Increment module active */
  module->module_active++;

  /* Entry dispatch */
  goto l_2;

  /* PROCEDURE DIVISION */

  /* Line: 71        : Entry     PGMARQ02                : EXEMPL01.cbl */
  l_2:;
#line 71 "EXEMPL01.cbl"
  ENTRY_PGMARQ02:	cob_nop ();
#line 105 "EXEMPL01.c"

  /* Line: 71        : Section   S000                    : EXEMPL01.cbl */
#line 71 "EXEMPL01.cbl"
  SECTION_S000:	cob_nop ();
#line 110 "EXEMPL01.c"

  /* Line: 72        : Paragraph P000-INICIO             : EXEMPL01.cbl */
#line 72 "EXEMPL01.cbl"
  PARAGRAPH_P000__INICIO_l_4:	cob_nop ();
#line 115 "EXEMPL01.c"

  /* Line: 73        : ACCEPT             : EXEMPL01.cbl */
#line 73 "EXEMPL01.cbl"
  cob_nop ();
#line 120 "EXEMPL01.c"
  cob_accept_date_yyyymmdd (&f_28);

  /* Line: 74        : MOVE               : EXEMPL01.cbl */
#line 74 "EXEMPL01.cbl"
  cob_nop ();
#line 126 "EXEMPL01.c"
  cob_move (COB_SET_FLD (f0, 2, b_28 + 6LL, &a_2), &f_30);

  /* Line: 75        : MOVE               : EXEMPL01.cbl */
#line 75 "EXEMPL01.cbl"
  cob_nop ();
#line 132 "EXEMPL01.c"
  cob_move (COB_SET_FLD (f0, 2, b_28 + 4LL, &a_2), &f_32);

  /* Line: 76        : MOVE               : EXEMPL01.cbl */
#line 76 "EXEMPL01.cbl"
  cob_nop ();
#line 138 "EXEMPL01.c"
  cob_move (COB_SET_FLD (f0, 4, b_28 + 0LL, &a_2), &f_34);

  /* Line: 78        : ACCEPT             : EXEMPL01.cbl */
#line 78 "EXEMPL01.cbl"
  cob_nop ();
#line 144 "EXEMPL01.c"
  cob_accept_time (&f_35);

  /* Line: 79        : MOVE               : EXEMPL01.cbl */
#line 79 "EXEMPL01.cbl"
  cob_nop ();
#line 150 "EXEMPL01.c"
  cob_move (COB_SET_FLD (f0, 2, b_35 + 0LL, &a_2), &f_37);

  /* Line: 80        : MOVE               : EXEMPL01.cbl */
#line 80 "EXEMPL01.cbl"
  cob_nop ();
#line 156 "EXEMPL01.c"
  cob_move (COB_SET_FLD (f0, 2, b_35 + 2LL, &a_2), &f_39);

  /* Line: 81        : MOVE               : EXEMPL01.cbl */
#line 81 "EXEMPL01.cbl"
  cob_nop ();
#line 162 "EXEMPL01.c"
  cob_move (COB_SET_FLD (f0, 2, b_35 + 4LL, &a_2), &f_41);

  /* Line: 83        : SET                : EXEMPL01.cbl */
#line 83 "EXEMPL01.cbl"
  cob_nop ();
#line 168 "EXEMPL01.c"
  *(b_49) = 78;

  /* Line: 85        : PERFORM            : EXEMPL01.cbl */
#line 85 "EXEMPL01.cbl"
  cob_nop ();
#line 174 "EXEMPL01.c"
  /* PERFORM P010-ABERTURA */
  frame_ptr++;
  if (unlikely(frame_ptr == frame_overflow))
  	cob_fatal_error (COB_FERROR_STACK);
  frame_ptr->perform_through = 7;
  frame_ptr->return_address_ptr = &&l_24;
  goto l_7;
  l_24:
  frame_ptr--;

  /* Line: 86        : PERFORM            : EXEMPL01.cbl */
#line 86 "EXEMPL01.cbl"
  cob_nop ();
#line 188 "EXEMPL01.c"
  for (;;)
  {
    /* Line: 86        : UNTIL              : EXEMPL01.cbl */
#line 86 "EXEMPL01.cbl"
    cob_nop ();
#line 194 "EXEMPL01.c"
    if (((int)(int)(*(b_49) - (unsigned char)'S') == 0))
      break;
    /* PERFORM P020-LEITURA */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 10;
    frame_ptr->return_address_ptr = &&l_25;
    goto l_10;
    l_25:
    frame_ptr--;
  }

  /* Line: 87        : PERFORM            : EXEMPL01.cbl */
#line 87 "EXEMPL01.cbl"
  cob_nop ();
#line 211 "EXEMPL01.c"
  /* PERFORM P800-FECHAR */
  frame_ptr++;
  if (unlikely(frame_ptr == frame_overflow))
  	cob_fatal_error (COB_FERROR_STACK);
  frame_ptr->perform_through = 13;
  frame_ptr->return_address_ptr = &&l_26;
  goto l_13;
  l_26:
  frame_ptr--;

  /* Line: 88        : PERFORM            : EXEMPL01.cbl */
#line 88 "EXEMPL01.cbl"
  cob_nop ();
#line 225 "EXEMPL01.c"
  /* PERFORM P950-TERMINO */
  frame_ptr++;
  if (unlikely(frame_ptr == frame_overflow))
  	cob_fatal_error (COB_FERROR_STACK);
  frame_ptr->perform_through = 19;
  frame_ptr->return_address_ptr = &&l_27;
  goto l_19;
  l_27:
  frame_ptr--;

  /* Line: 89        : Paragraph P000-EXIT               : EXEMPL01.cbl */
#line 89 "EXEMPL01.cbl"
  PARAGRAPH_P000__EXIT_l_5:	cob_nop ();
#line 239 "EXEMPL01.c"

  /* Line: 90        : EXIT               : EXEMPL01.cbl */
#line 90 "EXEMPL01.cbl"
  cob_nop ();
#line 244 "EXEMPL01.c"

  /* Line: 92        : Section   S010                    : EXEMPL01.cbl */
#line 92 "EXEMPL01.cbl"
  SECTION_S010:	cob_nop ();
#line 249 "EXEMPL01.c"

  /* Line: 93        : Paragraph P010-ABERTURA           : EXEMPL01.cbl */
  l_7:;
#line 93 "EXEMPL01.cbl"
  PARAGRAPH_P010__ABERTURA_l_7:	cob_nop ();
#line 255 "EXEMPL01.c"

  /* Line: 94        : OPEN               : EXEMPL01.cbl */
#line 94 "EXEMPL01.cbl"
  cob_nop ();
#line 260 "EXEMPL01.c"
  cob_open (h_STUDENT, COB_OPEN_INPUT, 0, &f_25);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* USE PROCEDURE Default Error Handler */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_28;
    goto l_1;
    l_28:
    frame_ptr--;
  }

  /* Line: 95        : IF                 : EXEMPL01.cbl */
#line 95 "EXEMPL01.cbl"
  cob_nop ();
#line 278 "EXEMPL01.c"
  if (((int)cob_numeric_display_cmp_zero (&f_25) != 0))
  {

    /* Line: 96        : MOVE               : EXEMPL01.cbl */
#line 96 "EXEMPL01.cbl"
    cob_nop ();
#line 285 "EXEMPL01.c"
    memcpy (b_26, "ERRO NO INPUT DO ARQUIVO STUDENT   ", 35);

    /* Line: 97        : MOVE               : EXEMPL01.cbl */
#line 97 "EXEMPL01.cbl"
    cob_nop ();
#line 291 "EXEMPL01.c"
    memcpy (b_27, b_25, 2);

    /* Line: 98        : PERFORM            : EXEMPL01.cbl */
#line 98 "EXEMPL01.cbl"
    cob_nop ();
#line 297 "EXEMPL01.c"
    /* PERFORM P900-DISPLAY */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 16;
    frame_ptr->return_address_ptr = &&l_29;
    goto l_16;
    l_29:
    frame_ptr--;
  }

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 7)
    goto *frame_ptr->return_address_ptr;

  /* Line: 100       : Paragraph P010-EXIT               : EXEMPL01.cbl */
#line 100 "EXEMPL01.cbl"
  PARAGRAPH_P010__EXIT_l_8:	cob_nop ();
#line 316 "EXEMPL01.c"

  /* Line: 101       : EXIT               : EXEMPL01.cbl */
#line 101 "EXEMPL01.cbl"
  cob_nop ();
#line 321 "EXEMPL01.c"

  /* Line: 103       : Section   S020                    : EXEMPL01.cbl */
#line 103 "EXEMPL01.cbl"
  SECTION_S020:	cob_nop ();
#line 326 "EXEMPL01.c"

  /* Line: 104       : Paragraph P020-LEITURA            : EXEMPL01.cbl */
  l_10:;
#line 104 "EXEMPL01.cbl"
  PARAGRAPH_P020__LEITURA_l_10:	cob_nop ();
#line 332 "EXEMPL01.c"

  /* Line: 105       : READ               : EXEMPL01.cbl */
#line 105 "EXEMPL01.cbl"
  cob_nop ();
#line 337 "EXEMPL01.c"
  cob_read_next (h_STUDENT, &f_25, 1);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    if (cob_glob_ptr->cob_exception_code == 0x0501)
    {

      /* Line: 107       : SET                : EXEMPL01.cbl */
#line 107 "EXEMPL01.cbl"
      cob_nop ();
#line 347 "EXEMPL01.c"
      *(b_49) = 83;
    }
    else
    {
      /* USE PROCEDURE Default Error Handler */
      frame_ptr++;
      if (unlikely(frame_ptr == frame_overflow))
      	cob_fatal_error (COB_FERROR_STACK);
      frame_ptr->perform_through = 1;
      frame_ptr->return_address_ptr = &&l_30;
      goto l_1;
      l_30:
      frame_ptr--;
    }
  }
  else
  {
    memcpy (b_21, b_20, 30);

    /* Line: 109       : ADD                : EXEMPL01.cbl */
#line 109 "EXEMPL01.cbl"
    cob_nop ();
#line 370 "EXEMPL01.c"
    cob_add_int (&f_48, 1, 0);

    /* Line: 110       : DISPLAY            : EXEMPL01.cbl */
#line 110 "EXEMPL01.cbl"
    cob_nop ();
#line 376 "EXEMPL01.c"
    cob_display (0, 1, 3, &f_23, &c_1, &f_24);
  }

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 10)
    goto *frame_ptr->return_address_ptr;

  /* Line: 112       : Paragraph P020-EXIT               : EXEMPL01.cbl */
#line 112 "EXEMPL01.cbl"
  PARAGRAPH_P020__EXIT_l_11:	cob_nop ();
#line 387 "EXEMPL01.c"

  /* Line: 113       : EXIT               : EXEMPL01.cbl */
#line 113 "EXEMPL01.cbl"
  cob_nop ();
#line 392 "EXEMPL01.c"

  /* Line: 115       : Section   S800                    : EXEMPL01.cbl */
#line 115 "EXEMPL01.cbl"
  SECTION_S800:	cob_nop ();
#line 397 "EXEMPL01.c"

  /* Line: 116       : Paragraph P800-FECHAR             : EXEMPL01.cbl */
  l_13:;
#line 116 "EXEMPL01.cbl"
  PARAGRAPH_P800__FECHAR_l_13:	cob_nop ();
#line 403 "EXEMPL01.c"

  /* Line: 117       : CLOSE              : EXEMPL01.cbl */
#line 117 "EXEMPL01.cbl"
  cob_nop ();
#line 408 "EXEMPL01.c"
  cob_close (h_STUDENT, &f_25, 0, 0);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* USE PROCEDURE Default Error Handler */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_31;
    goto l_1;
    l_31:
    frame_ptr--;
  }

  /* Line: 118       : IF                 : EXEMPL01.cbl */
#line 118 "EXEMPL01.cbl"
  cob_nop ();
#line 426 "EXEMPL01.c"
  if (((int)cob_numeric_display_cmp_zero (&f_25) != 0))
  {

    /* Line: 119       : MOVE               : EXEMPL01.cbl */
#line 119 "EXEMPL01.cbl"
    cob_nop ();
#line 433 "EXEMPL01.c"
    memcpy (b_26, "ERRO AO FECHAR O ARQUIVO STUDENT   ", 35);

    /* Line: 120       : MOVE               : EXEMPL01.cbl */
#line 120 "EXEMPL01.cbl"
    cob_nop ();
#line 439 "EXEMPL01.c"
    memcpy (b_27, b_25, 2);

    /* Line: 121       : PERFORM            : EXEMPL01.cbl */
#line 121 "EXEMPL01.cbl"
    cob_nop ();
#line 445 "EXEMPL01.c"
    /* PERFORM P900-DISPLAY */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 16;
    frame_ptr->return_address_ptr = &&l_32;
    goto l_16;
    l_32:
    frame_ptr--;
  }

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 13)
    goto *frame_ptr->return_address_ptr;

  /* Line: 123       : Paragraph P800-EXIT               : EXEMPL01.cbl */
#line 123 "EXEMPL01.cbl"
  PARAGRAPH_P800__EXIT_l_14:	cob_nop ();
#line 464 "EXEMPL01.c"

  /* Line: 124       : EXIT               : EXEMPL01.cbl */
#line 124 "EXEMPL01.cbl"
  cob_nop ();
#line 469 "EXEMPL01.c"

  /* Line: 126       : Section   S900                    : EXEMPL01.cbl */
#line 126 "EXEMPL01.cbl"
  SECTION_S900:	cob_nop ();
#line 474 "EXEMPL01.c"

  /* Line: 127       : Paragraph P900-DISPLAY            : EXEMPL01.cbl */
  l_16:;
#line 127 "EXEMPL01.cbl"
  PARAGRAPH_P900__DISPLAY_l_16:	cob_nop ();
#line 480 "EXEMPL01.c"

  /* Line: 128       : DISPLAY            : EXEMPL01.cbl */
#line 128 "EXEMPL01.cbl"
  cob_nop ();
#line 485 "EXEMPL01.c"
  cob_display (0, 1, 1, &c_2);

  /* Line: 129       : DISPLAY            : EXEMPL01.cbl */
#line 129 "EXEMPL01.cbl"
  cob_nop ();
#line 491 "EXEMPL01.c"
  cob_display (0, 1, 1, &c_3);

  /* Line: 130       : DISPLAY            : EXEMPL01.cbl */
#line 130 "EXEMPL01.cbl"
  cob_nop ();
#line 497 "EXEMPL01.c"
  cob_display (0, 1, 1, &c_2);

  /* Line: 131       : DISPLAY            : EXEMPL01.cbl */
#line 131 "EXEMPL01.cbl"
  cob_nop ();
#line 503 "EXEMPL01.c"
  cob_display (0, 1, 2, &c_4, &f_26);

  /* Line: 132       : DISPLAY            : EXEMPL01.cbl */
#line 132 "EXEMPL01.cbl"
  cob_nop ();
#line 509 "EXEMPL01.c"
  cob_display (0, 1, 2, &c_5, &f_27);

  /* Line: 133       : DISPLAY            : EXEMPL01.cbl */
#line 133 "EXEMPL01.cbl"
  cob_nop ();
#line 515 "EXEMPL01.c"
  cob_display (0, 1, 1, &c_2);

  /* Line: 134       : DISPLAY            : EXEMPL01.cbl */
#line 134 "EXEMPL01.cbl"
  cob_nop ();
#line 521 "EXEMPL01.c"
  cob_display (0, 1, 4, &c_6, &f_29, &c_7, &f_36);

  /* Line: 135       : DISPLAY            : EXEMPL01.cbl */
#line 135 "EXEMPL01.cbl"
  cob_nop ();
#line 527 "EXEMPL01.c"
  cob_display (0, 1, 4, &c_8, &f_29, &c_7, &f_42);

  /* Line: 136       : DISPLAY            : EXEMPL01.cbl */
#line 136 "EXEMPL01.cbl"
  cob_nop ();
#line 533 "EXEMPL01.c"
  cob_display (0, 1, 1, &c_2);

  /* Line: 137       : MOVE               : EXEMPL01.cbl */
#line 137 "EXEMPL01.cbl"
  cob_nop ();
#line 539 "EXEMPL01.c"
  b_2 = 4;

  /* Line: 138       : PERFORM            : EXEMPL01.cbl */
#line 138 "EXEMPL01.cbl"
  cob_nop ();
#line 545 "EXEMPL01.c"
  /* PERFORM P999-FIM */
  frame_ptr++;
  if (unlikely(frame_ptr == frame_overflow))
  	cob_fatal_error (COB_FERROR_STACK);
  frame_ptr->perform_through = 22;
  frame_ptr->return_address_ptr = &&l_33;
  goto l_22;
  l_33:
  frame_ptr--;

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 16)
    goto *frame_ptr->return_address_ptr;

  /* Line: 139       : Paragraph P900-EXIT               : EXEMPL01.cbl */
#line 139 "EXEMPL01.cbl"
  PARAGRAPH_P900__EXIT_l_17:	cob_nop ();
#line 563 "EXEMPL01.c"

  /* Line: 140       : EXIT               : EXEMPL01.cbl */
#line 140 "EXEMPL01.cbl"
  cob_nop ();
#line 568 "EXEMPL01.c"

  /* Line: 142       : Section   S950                    : EXEMPL01.cbl */
#line 142 "EXEMPL01.cbl"
  SECTION_S950:	cob_nop ();
#line 573 "EXEMPL01.c"

  /* Line: 143       : Paragraph P950-TERMINO            : EXEMPL01.cbl */
  l_19:;
#line 143 "EXEMPL01.cbl"
  PARAGRAPH_P950__TERMINO_l_19:	cob_nop ();
#line 579 "EXEMPL01.c"

  /* Line: 144       : ACCEPT             : EXEMPL01.cbl */
#line 144 "EXEMPL01.cbl"
  cob_nop ();
#line 584 "EXEMPL01.c"
  cob_accept_time (&f_35);

  /* Line: 145       : MOVE               : EXEMPL01.cbl */
#line 145 "EXEMPL01.cbl"
  cob_nop ();
#line 590 "EXEMPL01.c"
  cob_move (COB_SET_FLD (f0, 2, b_35 + 0LL, &a_2), &f_43);

  /* Line: 146       : MOVE               : EXEMPL01.cbl */
#line 146 "EXEMPL01.cbl"
  cob_nop ();
#line 596 "EXEMPL01.c"
  cob_move (COB_SET_FLD (f0, 2, b_35 + 2LL, &a_2), &f_45);

  /* Line: 147       : MOVE               : EXEMPL01.cbl */
#line 147 "EXEMPL01.cbl"
  cob_nop ();
#line 602 "EXEMPL01.c"
  cob_move (COB_SET_FLD (f0, 2, b_35 + 4LL, &a_2), &f_47);

  /* Line: 148       : DISPLAY            : EXEMPL01.cbl */
#line 148 "EXEMPL01.cbl"
  cob_nop ();
#line 608 "EXEMPL01.c"
  cob_display (0, 1, 1, &c_2);

  /* Line: 149       : DISPLAY            : EXEMPL01.cbl */
#line 149 "EXEMPL01.cbl"
  cob_nop ();
#line 614 "EXEMPL01.c"
  cob_display (0, 1, 1, &c_9);

  /* Line: 150       : DISPLAY            : EXEMPL01.cbl */
#line 150 "EXEMPL01.cbl"
  cob_nop ();
#line 620 "EXEMPL01.c"
  cob_display (0, 1, 1, &c_2);

  /* Line: 151       : DISPLAY            : EXEMPL01.cbl */
#line 151 "EXEMPL01.cbl"
  cob_nop ();
#line 626 "EXEMPL01.c"
  cob_display (0, 1, 2, &c_10, &f_48);

  /* Line: 152       : DISPLAY            : EXEMPL01.cbl */
#line 152 "EXEMPL01.cbl"
  cob_nop ();
#line 632 "EXEMPL01.c"
  cob_display (0, 1, 1, &c_2);

  /* Line: 153       : DISPLAY            : EXEMPL01.cbl */
#line 153 "EXEMPL01.cbl"
  cob_nop ();
#line 638 "EXEMPL01.c"
  cob_display (0, 1, 4, &c_6, &f_29, &c_7, &f_36);

  /* Line: 154       : DISPLAY            : EXEMPL01.cbl */
#line 154 "EXEMPL01.cbl"
  cob_nop ();
#line 644 "EXEMPL01.c"
  cob_display (0, 1, 4, &c_8, &f_29, &c_7, &f_42);

  /* Line: 155       : DISPLAY            : EXEMPL01.cbl */
#line 155 "EXEMPL01.cbl"
  cob_nop ();
#line 650 "EXEMPL01.c"
  cob_display (0, 1, 1, &c_2);

  /* Line: 156       : MOVE               : EXEMPL01.cbl */
#line 156 "EXEMPL01.cbl"
  cob_nop ();
#line 656 "EXEMPL01.c"
  b_2 = 0;

  /* Line: 157       : PERFORM            : EXEMPL01.cbl */
#line 157 "EXEMPL01.cbl"
  cob_nop ();
#line 662 "EXEMPL01.c"
  /* PERFORM P999-FIM */
  frame_ptr++;
  if (unlikely(frame_ptr == frame_overflow))
  	cob_fatal_error (COB_FERROR_STACK);
  frame_ptr->perform_through = 22;
  frame_ptr->return_address_ptr = &&l_34;
  goto l_22;
  l_34:
  frame_ptr--;

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 19)
    goto *frame_ptr->return_address_ptr;

  /* Line: 158       : Paragraph P950-EXIT               : EXEMPL01.cbl */
#line 158 "EXEMPL01.cbl"
  PARAGRAPH_P950__EXIT_l_20:	cob_nop ();
#line 680 "EXEMPL01.c"

  /* Line: 159       : EXIT               : EXEMPL01.cbl */
#line 159 "EXEMPL01.cbl"
  cob_nop ();
#line 685 "EXEMPL01.c"

  /* Line: 161       : Section   S999                    : EXEMPL01.cbl */
#line 161 "EXEMPL01.cbl"
  SECTION_S999:	cob_nop ();
#line 690 "EXEMPL01.c"

  /* Line: 162       : Paragraph P999-FIM                : EXEMPL01.cbl */
  l_22:;
#line 162 "EXEMPL01.cbl"
  PARAGRAPH_P999__FIM_l_22:	cob_nop ();
#line 696 "EXEMPL01.c"

  /* Line: 163       : STOP RUN           : EXEMPL01.cbl */
#line 163 "EXEMPL01.cbl"
  cob_nop ();
#line 701 "EXEMPL01.c"
  cob_stop_run (b_2);

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 22)
    goto *frame_ptr->return_address_ptr;

  /* Line: 164       : Paragraph P999-EXIT               : EXEMPL01.cbl */
#line 164 "EXEMPL01.cbl"
  PARAGRAPH_P999__EXIT_l_23:	cob_nop ();
#line 711 "EXEMPL01.c"

  /* Line: 165       : EXIT               : EXEMPL01.cbl */
#line 165 "EXEMPL01.cbl"
  cob_nop ();
#line 716 "EXEMPL01.c"

  /* Program exit */

  exit_program:

  /* Decrement module active count */
  if (module->module_active) {
  	module->module_active--;
  }

  /* Pop module stack */
  cob_module_leave (module);

  /* Program return */
  return b_2;


  /* Line: 0         : Paragraph Default Error Handler   : EXEMPL01.cbl */
  l_1:;

  if (!(cob_glob_ptr->cob_error_file->flag_select_features & COB_SELECT_FILE_STATUS))
  	cob_fatal_error (COB_FERROR_FILE);

  /* Implicit Default Error Handler return */
  if (frame_ptr->perform_through == 1)
    goto *frame_ptr->return_address_ptr;

  /* Fatal error if reached */
  cob_fatal_error (COB_FERROR_CODEGEN);

  P_cgerror:
  	cob_fatal_error (COB_FERROR_CODEGEN);


  /* Program initialization */
  P_initialize:

  cob_module_path = cob_glob_ptr->cob_main_argv0;

  PGMARQ02_module_init (module);

  module->collating_sequence = NULL;
  module->crt_status = NULL;
  module->cursor_pos = NULL;
  module->xml_code = NULL;
  module->xml_event = NULL;
  module->xml_information = NULL;
  module->xml_namespace = NULL;
  module->xml_namespace_prefix = NULL;
  module->xml_nnamespace = NULL;
  module->xml_nnamespace_prefix = NULL;
  module->xml_ntext = NULL;
  module->xml_text = NULL;
  module->json_code = NULL;
  module->json_status = NULL;

  /* Initialize cancel callback */
  cob_set_cancel (module);

  /* Initialize WORKING-STORAGE */
  /* initialize field RETURN-CODE */
  b_2 = 0;

  /* initialize field WS-DADOS */
#line 26 "EXEMPL01.cbl"
  cob_nop ();
#line 783 "EXEMPL01.c"
  memset (b_21, 32, 30);


  /* initialize field WS-FS-STU */
#line 32 "EXEMPL01.cbl"
  cob_nop ();
#line 790 "EXEMPL01.c"
  memset (b_25, 48, 2);

  /* initialize field WS-MSG-A */
#line 34 "EXEMPL01.cbl"
  cob_nop ();
#line 796 "EXEMPL01.c"
  memset (b_26, 32, 35);

  /* initialize field WS-MSG-B */
#line 35 "EXEMPL01.cbl"
  cob_nop ();
#line 802 "EXEMPL01.c"
  memset (b_27, 48, 2);

  /* initialize field WS-DATA */
#line 37 "EXEMPL01.cbl"
  cob_nop ();
#line 808 "EXEMPL01.c"
  memset (b_28, 48, 8);

  /* initialize field WS-DD */
#line 40 "EXEMPL01.cbl"
  cob_nop ();
#line 814 "EXEMPL01.c"
  memset (b_29, 48, 2);
  /* initialize field FILLER 2 */
#line 41 "EXEMPL01.cbl"
  cob_nop ();
#line 819 "EXEMPL01.c"
  *(cob_u8_ptr)(b_29 + 2) = (unsigned char)'/';
  /* initialize field WS-MM */
#line 42 "EXEMPL01.cbl"
  cob_nop ();
#line 824 "EXEMPL01.c"
  memset (b_29 + 3, 48, 2);
  /* initialize field FILLER 3 */
#line 43 "EXEMPL01.cbl"
  cob_nop ();
#line 829 "EXEMPL01.c"
  *(cob_u8_ptr)(b_29 + 5) = (unsigned char)'/';
  /* initialize field WS-AA */
#line 44 "EXEMPL01.cbl"
  cob_nop ();
#line 834 "EXEMPL01.c"
  memset (b_29 + 6, 48, 4);

  /* initialize field WS-HORA */
#line 46 "EXEMPL01.cbl"
  cob_nop ();
#line 840 "EXEMPL01.c"
  memset (b_35, 48, 8);

  /* initialize field WS-HR-I */
#line 49 "EXEMPL01.cbl"
  cob_nop ();
#line 846 "EXEMPL01.c"
  memset (b_36, 48, 2);
  /* initialize field FILLER 4 */
#line 50 "EXEMPL01.cbl"
  cob_nop ();
#line 851 "EXEMPL01.c"
  *(cob_u8_ptr)(b_36 + 2) = (unsigned char)':';
  /* initialize field WS-MI-I */
#line 51 "EXEMPL01.cbl"
  cob_nop ();
#line 856 "EXEMPL01.c"
  memset (b_36 + 3, 48, 2);
  /* initialize field FILLER 5 */
#line 52 "EXEMPL01.cbl"
  cob_nop ();
#line 861 "EXEMPL01.c"
  *(cob_u8_ptr)(b_36 + 5) = (unsigned char)':';
  /* initialize field WS-SE-I */
#line 53 "EXEMPL01.cbl"
  cob_nop ();
#line 866 "EXEMPL01.c"
  memset (b_36 + 6, 48, 2);

  /* initialize field WS-HR-F */
#line 55 "EXEMPL01.cbl"
  cob_nop ();
#line 872 "EXEMPL01.c"
  memset (b_42, 48, 2);
  /* initialize field FILLER 6 */
#line 56 "EXEMPL01.cbl"
  cob_nop ();
#line 877 "EXEMPL01.c"
  *(cob_u8_ptr)(b_42 + 2) = (unsigned char)':';
  /* initialize field WS-MI-F */
#line 57 "EXEMPL01.cbl"
  cob_nop ();
#line 882 "EXEMPL01.c"
  memset (b_42 + 3, 48, 2);
  /* initialize field FILLER 7 */
#line 58 "EXEMPL01.cbl"
  cob_nop ();
#line 887 "EXEMPL01.c"
  *(cob_u8_ptr)(b_42 + 5) = (unsigned char)':';
  /* initialize field WS-SE-F */
#line 59 "EXEMPL01.cbl"
  cob_nop ();
#line 892 "EXEMPL01.c"
  memset (b_42 + 6, 48, 2);

  /* initialize field WS-LER-STU */
#line 61 "EXEMPL01.cbl"
  cob_nop ();
#line 898 "EXEMPL01.c"
  memset (b_48, 48, 2);

  /* initialize field WS-OK */
#line 65 "EXEMPL01.cbl"
  cob_nop ();
#line 904 "EXEMPL01.c"
  *(cob_u8_ptr)(b_49) = (unsigned char)'N';


  /* File initialization for STUDENT */
  cob_file_malloc (&h_STUDENT, NULL, 0, 0);
  h_STUDENT->select_name = (const char *)"STUDENT";
  h_STUDENT->file_status = h_STUDENT_status;
  memset (h_STUDENT_status, '0', 2);
  h_STUDENT->assign = (cob_field *)&c_11;
  h_STUDENT->record = &f_20;
  h_STUDENT->variable_record = NULL;
  h_STUDENT->record_min = 0;
  h_STUDENT->record_max = 30;
  h_STUDENT->file = NULL;
  h_STUDENT->organization = 1;
  h_STUDENT->access_mode = 1;
  h_STUDENT->lock_mode = 0;
  h_STUDENT->open_mode = 0;
  h_STUDENT->flag_optional = 0;
  h_STUDENT->flag_line_adv = 0;
  h_STUDENT->flag_select_features = 1;

  if (0 == 1) goto P_cgerror;
  initialized = 1;
  goto P_ret_initialize;

  P_dump:
    return 0;


  /* CANCEL callback handling */
  P_cancel:

  if (!initialized)
  	return 0;
  if (module && module->module_active)
  	cob_fatal_error (COB_FERROR_CANCEL);

  initialized = 0;

  P_clear_decimal:
  return 0;

}

/* End PROGRAM-ID 'PGMARQ02' */

/* Initialize module structure for PGMARQ02 */
static void PGMARQ02_module_init (cob_module *module)
{
  module->module_name = "PGMARQ02";
  module->module_formatted_date = COB_MODULE_FORMATTED_DATE;
  module->module_source = COB_SOURCE_FILE;
  module->gc_version = COB_PACKAGE_VERSION;
  module->module_entry.funcptr = (void *(*)())PGMARQ02;
  module->module_cancel.funcptr = (void *(*)())PGMARQ02_;
  module->module_ref_count = NULL;
  module->module_path = &cob_module_path;
  module->module_active = 0;
  module->module_date = COB_MODULE_DATE;
  module->module_time = COB_MODULE_TIME;
  module->module_type = 0;
  module->module_param_cnt = 0;
  module->ebcdic_sign = 0;
  module->decimal_point = ',';
  module->currency_symbol = '$';
  module->numeric_separator = '.';
  module->flag_filename_mapping = 1;
  module->flag_binary_truncate = 1;
  module->flag_pretty_display = 1;
  module->flag_host_sign = 0;
  module->flag_no_phys_canc = 1;
  module->flag_main = 1;
  module->flag_fold_call = 0;
  module->flag_exit_program = 0;
  module->flag_debug_trace = 0;
  module->flag_dump_ready = 0;
  module->xml_mode = 1;
  module->module_stmt = 0;
  module->module_sources = NULL;
}

/* End functions */

