/* Generated by           cobc 3.3-dev.0 */
/* Generated from         INITIALIZE.cbl */
/* Generated at           Mar 08 2026 12:28:22 */
/* GnuCOBOL build date    Mar 06 2024 10:59:48 */
/* GnuCOBOL package date  Mar 06 2024 09:58:52 UTC */
/* Compile command        C:\Program Files\GnuCOBOL\bin\cobc.exe -x -g INITIALIZE.cbl */

#include <string.h> /* for memcpy, memcmp and friends */
#define  COB_KEYWORD_INLINE __inline
#include <libcob.h>

#define  COB_SOURCE_FILE		"INITIALIZE.cbl"
#define  COB_PACKAGE_VERSION		"3.3-dev"
#define  COB_PATCH_LEVEL		0
#define  COB_MODULE_FORMATTED_DATE	"Mar 08 2026 12:28:22"
#define  COB_MODULE_DATE		20260308
#define  COB_MODULE_TIME		122822

/* Global variables */
#include "INITIALIZE.c.h"

/* Function prototypes */

static int		PGM__INITIALIZE ();
static int		PGM__INITIALIZE_ (const int);
static void		PGM__INITIALIZE_module_init (cob_module *module);

/* Main function */
int
main (int argc, char **argv)
{
  cob_init (argc, argv);
  cob_stop_run (PGM__INITIALIZE ());
}

/* Functions */

static void gc_module_so_init () __attribute__ ((constructor));
static void gc_module_so_init ()
{
  cob_check_version (COB_SOURCE_FILE, COB_PACKAGE_VERSION, COB_PATCH_LEVEL);
}

/* PROGRAM-ID 'PGM-INITIALIZE' */

/* ENTRY 'PGM__INITIALIZE' */

static int
PGM__INITIALIZE ()
{
  return PGM__INITIALIZE_ (0);
}

static int
PGM__INITIALIZE_ (const int entry)
{
  /* Program local variables */
  #include "INITIALIZE.c.l.h"

  /* Start of function code */

  /* CANCEL callback */
  if (unlikely(entry < 0)) {
  	if (entry == -10)
  		goto P_dump;
  	if (entry == -20)
  		goto P_clear_decimal;
  	goto P_cancel;
  }

  /* Check initialized, check module allocated, */
  /* set global pointer, */
  /* push module stack, save call parameter count */
  if (cob_module_global_enter (&module, &cob_glob_ptr, 0, entry, 0))
  	return -1;

  /* Set address of module parameter list */
  module->cob_procedure_params = cob_procedure_params;

  /* Set frame stack pointer */
  frame_ptr = frame_stack;
  frame_ptr->perform_through = 0;
  frame_ptr->return_address_ptr = &&P_cgerror;
  frame_overflow = frame_ptr + 255 - 1;

  /* Initialize rest of program */
  if (unlikely(initialized == 0)) {
  	goto P_initialize;
  }
  P_ret_initialize:

  /* Increment module active */
  module->module_active++;

  /* Entry dispatch */
  goto l_2;

  /* PROCEDURE DIVISION */

  /* Line: 18        : Entry     PGM-INITIALIZE          : INITIALIZE.cbl */
  l_2:;
#line 18 "INITIALIZE.cbl"
  ENTRY_PGM__INITIALIZE:	cob_nop ();
#line 105 "INITIALIZE.c"

  /* Line: 18        : Section   S000-INI                : INITIALIZE.cbl */
#line 18 "INITIALIZE.cbl"
  SECTION_S000__INI:	cob_nop ();
#line 110 "INITIALIZE.c"

  /* Line: 19        : Paragraph P000-INI                : INITIALIZE.cbl */
#line 19 "INITIALIZE.cbl"
  PARAGRAPH_P000__INI_l_4:	cob_nop ();
#line 115 "INITIALIZE.c"

  /* Line: 20        : DISPLAY            : INITIALIZE.cbl */
#line 20 "INITIALIZE.cbl"
  cob_nop ();
#line 120 "INITIALIZE.c"
  cob_display (0, 1, 1, &c_1);

  /* Line: 21        : DISPLAY            : INITIALIZE.cbl */
#line 21 "INITIALIZE.cbl"
  cob_nop ();
#line 126 "INITIALIZE.c"
  cob_display (0, 1, 1, &f_17);

  /* Line: 23        : INITIALIZE         : INITIALIZE.cbl */
#line 23 "INITIALIZE.cbl"
  cob_nop ();
#line 132 "INITIALIZE.c"
  memset (b_17, 32, 10);
  memset (b_17 + 15, 48, 2);

  /* Line: 26        : DISPLAY            : INITIALIZE.cbl */
#line 26 "INITIALIZE.cbl"
  cob_nop ();
#line 139 "INITIALIZE.c"
  cob_display (0, 1, 1, &c_2);

  /* Line: 27        : DISPLAY            : INITIALIZE.cbl */
#line 27 "INITIALIZE.cbl"
  cob_nop ();
#line 145 "INITIALIZE.c"
  cob_display (0, 1, 1, &f_17);

  /* Line: 29        : INITIALIZE         : INITIALIZE.cbl */
#line 29 "INITIALIZE.cbl"
  cob_nop ();
#line 151 "INITIALIZE.c"
  memcpy (b_17, "JOB       ", 10);
  memset (b_17 + 15, 57, 2);

  /* Line: 32        : DISPLAY            : INITIALIZE.cbl */
#line 32 "INITIALIZE.cbl"
  cob_nop ();
#line 158 "INITIALIZE.c"
  cob_display (0, 1, 1, &c_3);

  /* Line: 33        : DISPLAY            : INITIALIZE.cbl */
#line 33 "INITIALIZE.cbl"
  cob_nop ();
#line 164 "INITIALIZE.c"
  cob_display (0, 1, 1, &f_17);

  /* Line: 35        : DISPLAY            : INITIALIZE.cbl */
#line 35 "INITIALIZE.cbl"
  cob_nop ();
#line 170 "INITIALIZE.c"
  cob_display (0, 1, 1, &c_4);

  /* Line: 36        : INITIALIZE         : INITIALIZE.cbl */
#line 36 "INITIALIZE.cbl"
  cob_nop ();
#line 176 "INITIALIZE.c"
  memset (b_17, (unsigned char)' ', 10);
  memset (b_17 + 15, (unsigned char)'0', 2);

  /* Line: 37        : DISPLAY            : INITIALIZE.cbl */
#line 37 "INITIALIZE.cbl"
  cob_nop ();
#line 183 "INITIALIZE.c"
  cob_display (0, 1, 1, &f_17);

  /* Line: 39        : Paragraph P000-EXIT               : INITIALIZE.cbl */
#line 39 "INITIALIZE.cbl"
  PARAGRAPH_P000__EXIT_l_5:	cob_nop ();
#line 189 "INITIALIZE.c"

  /* Line: 40        : EXIT               : INITIALIZE.cbl */
#line 40 "INITIALIZE.cbl"
  cob_nop ();
#line 194 "INITIALIZE.c"

  /* Line: 42        : Section   S900-STOP               : INITIALIZE.cbl */
#line 42 "INITIALIZE.cbl"
  SECTION_S900__STOP:	cob_nop ();
#line 199 "INITIALIZE.c"

  /* Line: 43        : Paragraph P900-STOP               : INITIALIZE.cbl */
#line 43 "INITIALIZE.cbl"
  PARAGRAPH_P900__STOP_l_7:	cob_nop ();
#line 204 "INITIALIZE.c"

  /* Line: 44        : STOP RUN           : INITIALIZE.cbl */
#line 44 "INITIALIZE.cbl"
  cob_nop ();
#line 209 "INITIALIZE.c"
  cob_stop_run (b_2);

  /* Line: 45        : Paragraph P900-EXIT               : INITIALIZE.cbl */
#line 45 "INITIALIZE.cbl"
  PARAGRAPH_P900__EXIT_l_8:	cob_nop ();
#line 215 "INITIALIZE.c"

  /* Program exit */

  exit_program:

  /* Decrement module active count */
  if (module->module_active) {
  	module->module_active--;
  }

  /* Pop module stack */
  cob_module_leave (module);

  /* Program return */
  return b_2;
  P_cgerror:
  	cob_fatal_error (COB_FERROR_CODEGEN);


  /* Program initialization */
  P_initialize:

  cob_module_path = cob_glob_ptr->cob_main_argv0;

  PGM__INITIALIZE_module_init (module);

  module->collating_sequence = NULL;
  module->crt_status = NULL;
  module->cursor_pos = NULL;
  module->xml_code = NULL;
  module->xml_event = NULL;
  module->xml_information = NULL;
  module->xml_namespace = NULL;
  module->xml_namespace_prefix = NULL;
  module->xml_nnamespace = NULL;
  module->xml_nnamespace_prefix = NULL;
  module->xml_ntext = NULL;
  module->xml_text = NULL;
  module->json_code = NULL;
  module->json_status = NULL;

  /* Initialize cancel callback */
  cob_set_cancel (module);

  /* Initialize WORKING-STORAGE */
  /* initialize field RETURN-CODE */
  b_2 = 0;

  /* initialize field WS-NOME */
#line 14 "INITIALIZE.cbl"
  cob_nop ();
#line 267 "INITIALIZE.c"
  memset (b_17, (unsigned char)' ', 10);
  /* initialize field FILLER 1 */
#line 15 "INITIALIZE.cbl"
  cob_nop ();
#line 272 "INITIALIZE.c"
  memcpy (b_17 + 10, "MOTTA", 5);
  /* initialize field WS-IDADE */
#line 16 "INITIALIZE.cbl"
  cob_nop ();
#line 277 "INITIALIZE.c"
  memcpy (b_17 + 15, "46", 2);


  if (0 == 1) goto P_cgerror;
  initialized = 1;
  goto P_ret_initialize;

  P_dump:
    return 0;


  /* CANCEL callback handling */
  P_cancel:

  if (!initialized)
  	return 0;
  if (module && module->module_active)
  	cob_fatal_error (COB_FERROR_CANCEL);

  initialized = 0;

  P_clear_decimal:
  return 0;

}

/* End PROGRAM-ID 'PGM-INITIALIZE' */

/* Initialize module structure for PGM-INITIALIZE */
static void PGM__INITIALIZE_module_init (cob_module *module)
{
  module->module_name = "PGM-INITIALIZE";
  module->module_formatted_date = COB_MODULE_FORMATTED_DATE;
  module->module_source = COB_SOURCE_FILE;
  module->gc_version = COB_PACKAGE_VERSION;
  module->module_entry.funcptr = (void *(*)())PGM__INITIALIZE;
  module->module_cancel.funcptr = (void *(*)())PGM__INITIALIZE_;
  module->module_ref_count = NULL;
  module->module_path = &cob_module_path;
  module->module_active = 0;
  module->module_date = COB_MODULE_DATE;
  module->module_time = COB_MODULE_TIME;
  module->module_type = 0;
  module->module_param_cnt = 0;
  module->ebcdic_sign = 0;
  module->decimal_point = '.';
  module->currency_symbol = '$';
  module->numeric_separator = ',';
  module->flag_filename_mapping = 1;
  module->flag_binary_truncate = 1;
  module->flag_pretty_display = 1;
  module->flag_host_sign = 0;
  module->flag_no_phys_canc = 1;
  module->flag_main = 1;
  module->flag_fold_call = 0;
  module->flag_exit_program = 0;
  module->flag_debug_trace = 0;
  module->flag_dump_ready = 0;
  module->xml_mode = 1;
  module->module_stmt = 0;
  module->module_sources = NULL;
}

/* End functions */

