/* Generated by           cobc 3.3-dev.0 */
/* Generated from         OLA-MUNDO.cbl */
/* Generated at           Mar 08 2026 10:54:19 */
/* GnuCOBOL build date    Mar 06 2024 10:59:48 */
/* GnuCOBOL package date  Mar 06 2024 09:58:52 UTC */
/* Compile command        C:\Program Files\GnuCOBOL\bin\cobc.exe -x -g OLA-MUNDO.cbl */

#include <string.h> /* for memcpy, memcmp and friends */
#define  COB_KEYWORD_INLINE __inline
#include <libcob.h>

#define  COB_SOURCE_FILE		"OLA-MUNDO.cbl"
#define  COB_PACKAGE_VERSION		"3.3-dev"
#define  COB_PATCH_LEVEL		0
#define  COB_MODULE_FORMATTED_DATE	"Mar 08 2026 10:54:19"
#define  COB_MODULE_DATE		20260308
#define  COB_MODULE_TIME		105419

/* Global variables */
#include "OLA-MUNDO.c.h"

/* Function prototypes */

static int		OLAMUNDO ();
static int		OLAMUNDO_ (const int);
static void		OLAMUNDO_module_init (cob_module *module);

/* Main function */
int
main (int argc, char **argv)
{
  cob_init (argc, argv);
  cob_stop_run (OLAMUNDO ());
}

/* Functions */

static void gc_module_so_init () __attribute__ ((constructor));
static void gc_module_so_init ()
{
  cob_check_version (COB_SOURCE_FILE, COB_PACKAGE_VERSION, COB_PATCH_LEVEL);
}

/* PROGRAM-ID 'OLAMUNDO' */

/* ENTRY 'OLAMUNDO' */

static int
OLAMUNDO ()
{
  return OLAMUNDO_ (0);
}

static int
OLAMUNDO_ (const int entry)
{
  /* Program local variables */
  #include "OLA-MUNDO.c.l.h"

  /* Start of function code */

  /* CANCEL callback */
  if (unlikely(entry < 0)) {
  	if (entry == -10)
  		goto P_dump;
  	if (entry == -20)
  		goto P_clear_decimal;
  	goto P_cancel;
  }

  /* Check initialized, check module allocated, */
  /* set global pointer, */
  /* push module stack, save call parameter count */
  if (cob_module_global_enter (&module, &cob_glob_ptr, 0, entry, 0))
  	return -1;

  /* Set address of module parameter list */
  module->cob_procedure_params = cob_procedure_params;

  /* Set frame stack pointer */
  frame_ptr = frame_stack;
  frame_ptr->perform_through = 0;
  frame_ptr->return_address_ptr = &&P_cgerror;
  frame_overflow = frame_ptr + 255 - 1;

  /* Initialize rest of program */
  if (unlikely(initialized == 0)) {
  	goto P_initialize;
  }
  P_ret_initialize:

  /* Increment module active */
  module->module_active++;

  /* Entry dispatch */
  goto l_2;

  /* PROCEDURE DIVISION */

  /* Line: 14        : Entry     OLAMUNDO                : OLA-MUNDO.cbl */
  l_2:;
#line 14 "OLA-MUNDO.cbl"
  ENTRY_OLAMUNDO:	cob_nop ();
#line 105 "OLA-MUNDO.c"

  /* Line: 14        : Paragraph 000-INICIO              : OLA-MUNDO.cbl */
#line 14 "OLA-MUNDO.cbl"
  PARAGRAPH_000__INICIO_l_4:	cob_nop ();
#line 110 "OLA-MUNDO.c"

  /* Line: 15        : DISPLAY            : OLA-MUNDO.cbl */
#line 15 "OLA-MUNDO.cbl"
  cob_nop ();
#line 115 "OLA-MUNDO.c"
  cob_display (0, 1, 2, &c_1, &f_17);

  /* Line: 16        : STOP RUN           : OLA-MUNDO.cbl */
#line 16 "OLA-MUNDO.cbl"
  cob_nop ();
#line 121 "OLA-MUNDO.c"
  cob_stop_run (b_2);

  /* Program exit */

  exit_program:

  /* Decrement module active count */
  if (module->module_active) {
  	module->module_active--;
  }

  /* Pop module stack */
  cob_module_leave (module);

  /* Program return */
  return b_2;
  P_cgerror:
  	cob_fatal_error (COB_FERROR_CODEGEN);


  /* Program initialization */
  P_initialize:

  cob_module_path = cob_glob_ptr->cob_main_argv0;

  OLAMUNDO_module_init (module);

  module->collating_sequence = NULL;
  module->crt_status = NULL;
  module->cursor_pos = NULL;
  module->xml_code = NULL;
  module->xml_event = NULL;
  module->xml_information = NULL;
  module->xml_namespace = NULL;
  module->xml_namespace_prefix = NULL;
  module->xml_nnamespace = NULL;
  module->xml_nnamespace_prefix = NULL;
  module->xml_ntext = NULL;
  module->xml_text = NULL;
  module->json_code = NULL;
  module->json_status = NULL;

  /* Initialize cancel callback */
  cob_set_cancel (module);

  /* Initialize WORKING-STORAGE */
  /* initialize field RETURN-CODE */
  b_2 = 0;

  /* initialize field WS-VAR1 */
#line 12 "OLA-MUNDO.cbl"
  cob_nop ();
#line 174 "OLA-MUNDO.c"
  memcpy (b_17, "OLA MUNDO!", 10);


  if (0 == 1) goto P_cgerror;
  initialized = 1;
  goto P_ret_initialize;

  P_dump:
    return 0;


  /* CANCEL callback handling */
  P_cancel:

  if (!initialized)
  	return 0;
  if (module && module->module_active)
  	cob_fatal_error (COB_FERROR_CANCEL);

  initialized = 0;

  P_clear_decimal:
  return 0;

}

/* End PROGRAM-ID 'OLAMUNDO' */

/* Initialize module structure for OLAMUNDO */
static void OLAMUNDO_module_init (cob_module *module)
{
  module->module_name = "OLAMUNDO";
  module->module_formatted_date = COB_MODULE_FORMATTED_DATE;
  module->module_source = COB_SOURCE_FILE;
  module->gc_version = COB_PACKAGE_VERSION;
  module->module_entry.funcptr = (void *(*)())OLAMUNDO;
  module->module_cancel.funcptr = (void *(*)())OLAMUNDO_;
  module->module_ref_count = NULL;
  module->module_path = &cob_module_path;
  module->module_active = 0;
  module->module_date = COB_MODULE_DATE;
  module->module_time = COB_MODULE_TIME;
  module->module_type = 0;
  module->module_param_cnt = 0;
  module->ebcdic_sign = 0;
  module->decimal_point = '.';
  module->currency_symbol = '$';
  module->numeric_separator = ',';
  module->flag_filename_mapping = 1;
  module->flag_binary_truncate = 1;
  module->flag_pretty_display = 1;
  module->flag_host_sign = 0;
  module->flag_no_phys_canc = 1;
  module->flag_main = 1;
  module->flag_fold_call = 0;
  module->flag_exit_program = 0;
  module->flag_debug_trace = 0;
  module->flag_dump_ready = 0;
  module->xml_mode = 1;
  module->module_stmt = 0;
  module->module_sources = NULL;
}

/* End functions */

