/* Generated by           cobc 3.3-dev.0 */
/* Generated from         OLA-MUNDO.cbl */
/* Generated at           Mar 08 2026 10:54:19 */
/* GnuCOBOL build date    Mar 06 2024 10:59:48 */
/* GnuCOBOL package date  Mar 06 2024 09:58:52 UTC */
/* Compile command        C:\Program Files\GnuCOBOL\bin\cobc.exe -x -g OLA-MUNDO.cbl */


/* Module path */
static const char		*cob_module_path = NULL;

/* Number of call parameters */
static int		cob_call_params = 0;

/* Attributes */

static const cob_field_attr a_1 =	{0x21,   0,   0, 0x1000, NULL};
static const cob_field_attr a_2 =	{0x21,   0,   0, 0x0000, NULL};


/* Constants */
static const cob_field c_1	= {23, (cob_u8_ptr)"MEU PRIMEIRO PROGRAMA: ", &a_1};


#define cob_nop	if (!module) cob_nop

