/* Generated by           cobc 3.3-dev.0 */
/* Generated from         STRING.cbl */
/* Generated at           Mar 08 2026 10:50:24 */
/* GnuCOBOL build date    Mar 06 2024 10:59:48 */
/* GnuCOBOL package date  Mar 06 2024 09:58:52 UTC */
/* Compile command        C:\Program Files\GnuCOBOL\bin\cobc.exe -x -g STRING.cbl */

/* Program local variables for 'PGM-STRING' */

/* Module initialization indicator */
static unsigned int	initialized = 0;

/* Module structure pointer */
static cob_module	*module = NULL;

/* Global variable pointer */
cob_global		*cob_glob_ptr;


/* LINKAGE SECTION (Items not referenced by USING clause) */
static unsigned char	*b_9 = NULL;  /* XML-NAMESPACE */
static unsigned char	*b_10 = NULL;  /* XML-NAMESPACE-PREFIX */
static unsigned char	*b_11 = NULL;  /* XML-NNAMESPACE */
static unsigned char	*b_12 = NULL;  /* XML-NNAMESPACE-PREFIX */
static unsigned char	*b_13 = NULL;  /* XML-NTEXT */
static unsigned char	*b_14 = NULL;  /* XML-TEXT */


/* Local cob_field items */
cob_field		f0;


/* Call parameters */
cob_field		*cob_procedure_params[1];

/* Perform frame stack */
struct cob_frame	*frame_overflow;
struct cob_frame	*frame_ptr;
struct cob_frame	frame_stack[255];


/* Data storage */
static int	b_2;	/* RETURN-CODE */
static cob_u8_t	b_17[45] __attribute__((aligned));	/* WS-CONTEUDO */
static cob_u8_t	b_18[45] __attribute__((aligned));	/* WS-TEXTO */
static cob_u8_t	b_19[2] __attribute__((aligned));	/* WS-PONTEIRO */

/* End of local data storage */


/* Fields (local) */
static cob_field f_17	= {45, b_17, &a_1};	/* WS-CONTEUDO */
static cob_field f_18	= {45, b_18, &a_1};	/* WS-TEXTO */
static cob_field f_19	= {2, b_19, &a_3};	/* WS-PONTEIRO */

/* End of fields */

