/* Generated by           cobc 3.3-dev.0 */
/* Generated from         STRING.cbl */
/* Generated at           Mar 08 2026 10:50:24 */
/* GnuCOBOL build date    Mar 06 2024 10:59:48 */
/* GnuCOBOL package date  Mar 06 2024 09:58:52 UTC */
/* Compile command        C:\Program Files\GnuCOBOL\bin\cobc.exe -x -g STRING.cbl */


/* Module path */
static const char		*cob_module_path = NULL;

/* Number of call parameters */
static int		cob_call_params = 0;

/* Attributes */

static const cob_field_attr a_1 =	{0x21,   0,   0, 0x0000, NULL};
static const cob_field_attr a_2 =	{0x21,   0,   0, 0x1000, NULL};
static const cob_field_attr a_3 =	{0x10,   2,   0, 0x0000, NULL};


/* Constants */
static const cob_field c_1	= {7, (cob_u8_ptr)"EMERSON", &a_2};
static const cob_field c_2	= {1, (cob_u8_ptr)" ", &a_2};
static const cob_field c_3	= {5, (cob_u8_ptr)"MOTTA", &a_2};
static const cob_field c_4	= {9, (cob_u8_ptr)"EXEMPLO1:", &a_2};
static const cob_field c_5	= {9, (cob_u8_ptr)"PROFESSOR", &a_2};
static const cob_field c_6	= {5, (cob_u8_ptr)"COBOL", &a_2};
static const cob_field c_7	= {10, (cob_u8_ptr)"EXEMPLO2: ", &a_2};
static const cob_field c_8	= {1, (cob_u8_ptr)";", &a_2};
static const cob_field c_9	= {10, (cob_u8_ptr)"EXEMPLO3: ", &a_2};
static const cob_field c_10	= {10, (cob_u8_ptr)"EXEMPLO4: ", &a_2};


#define cob_nop	if (!module) cob_nop

