/* Generated by           cobc 3.3-dev.0 */
/* Generated from         STRING.cbl */
/* Generated at           Mar 08 2026 10:50:24 */
/* GnuCOBOL build date    Mar 06 2024 10:59:48 */
/* GnuCOBOL package date  Mar 06 2024 09:58:52 UTC */
/* Compile command        C:\Program Files\GnuCOBOL\bin\cobc.exe -x -g STRING.cbl */

#include <string.h> /* for memcpy, memcmp and friends */
#define  COB_KEYWORD_INLINE __inline
#include <libcob.h>

#define  COB_SOURCE_FILE		"STRING.cbl"
#define  COB_PACKAGE_VERSION		"3.3-dev"
#define  COB_PATCH_LEVEL		0
#define  COB_MODULE_FORMATTED_DATE	"Mar 08 2026 10:50:24"
#define  COB_MODULE_DATE		20260308
#define  COB_MODULE_TIME		105024

/* Global variables */
#include "STRING.c.h"

/* Function prototypes */

static int		PGM__STRING ();
static int		PGM__STRING_ (const int);
static void		PGM__STRING_module_init (cob_module *module);

/* Main function */
int
main (int argc, char **argv)
{
  cob_init (argc, argv);
  cob_stop_run (PGM__STRING ());
}

/* Functions */

static void gc_module_so_init () __attribute__ ((constructor));
static void gc_module_so_init ()
{
  cob_check_version (COB_SOURCE_FILE, COB_PACKAGE_VERSION, COB_PATCH_LEVEL);
}

/* PROGRAM-ID 'PGM-STRING' */

/* ENTRY 'PGM__STRING' */

static int
PGM__STRING ()
{
  return PGM__STRING_ (0);
}

static int
PGM__STRING_ (const int entry)
{
  /* Program local variables */
  #include "STRING.c.l.h"

  /* Start of function code */

  /* CANCEL callback */
  if (unlikely(entry < 0)) {
  	if (entry == -10)
  		goto P_dump;
  	if (entry == -20)
  		goto P_clear_decimal;
  	goto P_cancel;
  }

  /* Check initialized, check module allocated, */
  /* set global pointer, */
  /* push module stack, save call parameter count */
  if (cob_module_global_enter (&module, &cob_glob_ptr, 0, entry, 0))
  	return -1;

  /* Set address of module parameter list */
  module->cob_procedure_params = cob_procedure_params;

  /* Set frame stack pointer */
  frame_ptr = frame_stack;
  frame_ptr->perform_through = 0;
  frame_ptr->return_address_ptr = &&P_cgerror;
  frame_overflow = frame_ptr + 255 - 1;

  /* Initialize rest of program */
  if (unlikely(initialized == 0)) {
  	goto P_initialize;
  }
  P_ret_initialize:

  /* Increment module active */
  module->module_active++;

  /* Entry dispatch */
  goto l_2;

  /* PROCEDURE DIVISION */

  /* Line: 16        : Entry     PGM-STRING              : STRING.cbl */
  l_2:;
#line 16 "STRING.cbl"
  ENTRY_PGM__STRING:	cob_nop ();
#line 105 "STRING.c"

  /* Line: 16        : Section   S000-INICIO             : STRING.cbl */
#line 16 "STRING.cbl"
  SECTION_S000__INICIO:	cob_nop ();
#line 110 "STRING.c"

  /* Line: 17        : Paragraph P001-INI                : STRING.cbl */
#line 17 "STRING.cbl"
  PARAGRAPH_P001__INI_l_4:	cob_nop ();
#line 115 "STRING.c"

  /* Line: 22        : PERFORM            : STRING.cbl */
#line 22 "STRING.cbl"
  cob_nop ();
#line 120 "STRING.c"
  /* PERFORM S010-EXEMPLOS */
  frame_ptr++;
  if (unlikely(frame_ptr == frame_overflow))
  	cob_fatal_error (COB_FERROR_STACK);
  frame_ptr->perform_through = 6;
  frame_ptr->return_address_ptr = &&l_21;
  goto l_6;
  l_21:
  frame_ptr--;

  /* Line: 23        : PERFORM            : STRING.cbl */
#line 23 "STRING.cbl"
  cob_nop ();
#line 134 "STRING.c"
  /* PERFORM P901-TERM */
  frame_ptr++;
  if (unlikely(frame_ptr == frame_overflow))
  	cob_fatal_error (COB_FERROR_STACK);
  frame_ptr->perform_through = 19;
  frame_ptr->return_address_ptr = &&l_22;
  goto l_19;
  l_22:
  frame_ptr--;

  /* Line: 25        : Paragraph P001-EXIT               : STRING.cbl */
#line 25 "STRING.cbl"
  PARAGRAPH_P001__EXIT_l_5:	cob_nop ();
#line 148 "STRING.c"

  /* Line: 26        : EXIT               : STRING.cbl */
#line 26 "STRING.cbl"
  cob_nop ();
#line 153 "STRING.c"

  /* Line: 28        : Section   S010-EXEMPLOS           : STRING.cbl */
  l_6:;
#line 28 "STRING.cbl"
  SECTION_S010__EXEMPLOS:	cob_nop ();
#line 159 "STRING.c"

  /* Line: 29        : Paragraph P011-EXEMPLO1           : STRING.cbl */
#line 29 "STRING.cbl"
  PARAGRAPH_P011__EXEMPLO1_l_7:	cob_nop ();
#line 164 "STRING.c"

  /* Line: 31        : STRING             : STRING.cbl */
#line 31 "STRING.cbl"
  cob_nop ();
#line 169 "STRING.c"
  cob_string_init (&f_17, NULL);
  cob_string_delimited (NULL);
  cob_string_append ((cob_field *)&c_1);
  cob_string_append ((cob_field *)&c_2);
  cob_string_append ((cob_field *)&c_3);
  cob_string_finish ();

  /* Line: 38        : DISPLAY            : STRING.cbl */
#line 38 "STRING.cbl"
  cob_nop ();
#line 180 "STRING.c"
  cob_display (0, 1, 1, &c_4);

  /* Line: 39        : DISPLAY            : STRING.cbl */
#line 39 "STRING.cbl"
  cob_nop ();
#line 186 "STRING.c"
  cob_display (0, 1, 1, &f_17);

  /* Line: 40        : DISPLAY            : STRING.cbl */
#line 40 "STRING.cbl"
  cob_nop ();
#line 192 "STRING.c"
  cob_display (0, 1, 1, &c_2);

  /* Line: 41        : PERFORM            : STRING.cbl */
#line 41 "STRING.cbl"
  cob_nop ();
#line 198 "STRING.c"
  /* PERFORM P801-INICIALIZA THRU P801-EXIT */
  frame_ptr++;
  if (unlikely(frame_ptr == frame_overflow))
  	cob_fatal_error (COB_FERROR_STACK);
  frame_ptr->perform_through = 17;
  frame_ptr->return_address_ptr = &&l_23;
  goto l_16;
  l_23:
  frame_ptr--;

  /* Line: 42        : Paragraph P011-EXIT               : STRING.cbl */
#line 42 "STRING.cbl"
  PARAGRAPH_P011__EXIT_l_8:	cob_nop ();
#line 212 "STRING.c"

  /* Line: 44        : Paragraph P012-EXEMPLO2           : STRING.cbl */
#line 44 "STRING.cbl"
  PARAGRAPH_P012__EXEMPLO2_l_9:	cob_nop ();
#line 217 "STRING.c"

  /* Line: 47        : MOVE               : STRING.cbl */
#line 47 "STRING.cbl"
  cob_nop ();
#line 222 "STRING.c"
  memcpy (b_18, "O ANDRE ESTA MINISTRANDO O CURSO             ", 45);

  /* Line: 48        : STRING             : STRING.cbl */
#line 48 "STRING.cbl"
  cob_nop ();
#line 228 "STRING.c"
  cob_string_init (&f_17, NULL);
  cob_string_delimited (NULL);
  cob_string_append ((cob_field *)&c_5);
  cob_string_append (COB_SET_FLD (f0, 7, b_18 + 1LL, &a_1));
  cob_string_append (COB_SET_FLD (f0, 19, b_18 + 13LL, &a_1));
  cob_string_append ((cob_field *)&c_2);
  cob_string_append ((cob_field *)&c_6);
  cob_string_finish ();

  /* Line: 57        : DISPLAY            : STRING.cbl */
#line 57 "STRING.cbl"
  cob_nop ();
#line 241 "STRING.c"
  cob_display (0, 1, 1, &c_7);

  /* Line: 58        : DISPLAY            : STRING.cbl */
#line 58 "STRING.cbl"
  cob_nop ();
#line 247 "STRING.c"
  cob_display (0, 1, 1, &f_17);

  /* Line: 59        : DISPLAY            : STRING.cbl */
#line 59 "STRING.cbl"
  cob_nop ();
#line 253 "STRING.c"
  cob_display (0, 1, 1, &c_2);

  /* Line: 60        : PERFORM            : STRING.cbl */
#line 60 "STRING.cbl"
  cob_nop ();
#line 259 "STRING.c"
  /* PERFORM P801-INICIALIZA THRU P801-EXIT */
  frame_ptr++;
  if (unlikely(frame_ptr == frame_overflow))
  	cob_fatal_error (COB_FERROR_STACK);
  frame_ptr->perform_through = 17;
  frame_ptr->return_address_ptr = &&l_24;
  goto l_16;
  l_24:
  frame_ptr--;

  /* Line: 61        : Paragraph P012-EXIT               : STRING.cbl */
#line 61 "STRING.cbl"
  PARAGRAPH_P012__EXIT_l_10:	cob_nop ();
#line 273 "STRING.c"

  /* Line: 63        : Paragraph P013-EXEMPLO3           : STRING.cbl */
#line 63 "STRING.cbl"
  PARAGRAPH_P013__EXEMPLO3_l_11:	cob_nop ();
#line 278 "STRING.c"

  /* Line: 66        : MOVE               : STRING.cbl */
#line 66 "STRING.cbl"
  cob_nop ();
#line 283 "STRING.c"
  memcpy (b_18, "O ANDRE;ESTA MINISTRANDO O CURSO             ", 45);

  /* Line: 67        : STRING             : STRING.cbl */
#line 67 "STRING.cbl"
  cob_nop ();
#line 289 "STRING.c"
  cob_string_init (&f_17, NULL);
  cob_string_delimited ((cob_field *)&c_8);
  cob_string_append (&f_18);
  cob_string_finish ();

  /* Line: 72        : DISPLAY            : STRING.cbl */
#line 72 "STRING.cbl"
  cob_nop ();
#line 298 "STRING.c"
  cob_display (0, 1, 1, &c_9);

  /* Line: 73        : DISPLAY            : STRING.cbl */
#line 73 "STRING.cbl"
  cob_nop ();
#line 304 "STRING.c"
  cob_display (0, 1, 1, &f_17);

  /* Line: 74        : DISPLAY            : STRING.cbl */
#line 74 "STRING.cbl"
  cob_nop ();
#line 310 "STRING.c"
  cob_display (0, 1, 1, &c_2);

  /* Line: 75        : PERFORM            : STRING.cbl */
#line 75 "STRING.cbl"
  cob_nop ();
#line 316 "STRING.c"
  /* PERFORM P801-INICIALIZA THRU P801-EXIT */
  frame_ptr++;
  if (unlikely(frame_ptr == frame_overflow))
  	cob_fatal_error (COB_FERROR_STACK);
  frame_ptr->perform_through = 17;
  frame_ptr->return_address_ptr = &&l_25;
  goto l_16;
  l_25:
  frame_ptr--;

  /* Line: 76        : Paragraph P013-EXIT               : STRING.cbl */
#line 76 "STRING.cbl"
  PARAGRAPH_P013__EXIT_l_12:	cob_nop ();
#line 330 "STRING.c"

  /* Line: 78        : Paragraph P014-EXEMPLO4           : STRING.cbl */
#line 78 "STRING.cbl"
  PARAGRAPH_P014__EXEMPLO4_l_13:	cob_nop ();
#line 335 "STRING.c"

  /* Line: 81        : MOVE               : STRING.cbl */
#line 81 "STRING.cbl"
  cob_nop ();
#line 340 "STRING.c"
  memcpy (b_18, "O ANDRE ESTA MINISTRANDO O CURSO             ", 45);

  /* Line: 82        : SET                : STRING.cbl */
#line 82 "STRING.cbl"
  cob_nop ();
#line 346 "STRING.c"
  memcpy (b_19, "01", 2);

  /* Line: 84        : STRING             : STRING.cbl */
#line 84 "STRING.cbl"
  cob_nop ();
#line 352 "STRING.c"
  cob_string_init (&f_17, &f_19);
  cob_string_delimited (NULL);
  cob_string_append ((cob_field *)&c_5);
  cob_string_append (COB_SET_FLD (f0, 31, b_18 + 1LL, &a_1));
  cob_string_finish ();

  /* Line: 91        : DISPLAY            : STRING.cbl */
#line 91 "STRING.cbl"
  cob_nop ();
#line 362 "STRING.c"
  cob_display (0, 1, 1, &c_10);

  /* Line: 92        : DISPLAY            : STRING.cbl */
#line 92 "STRING.cbl"
  cob_nop ();
#line 368 "STRING.c"
  cob_display (0, 1, 1, &f_17);

  /* Line: 93        : DISPLAY            : STRING.cbl */
#line 93 "STRING.cbl"
  cob_nop ();
#line 374 "STRING.c"
  cob_display (0, 1, 1, &f_19);

  /* Line: 94        : DISPLAY            : STRING.cbl */
#line 94 "STRING.cbl"
  cob_nop ();
#line 380 "STRING.c"
  cob_display (0, 1, 1, &c_2);

  /* Line: 95        : PERFORM            : STRING.cbl */
#line 95 "STRING.cbl"
  cob_nop ();
#line 386 "STRING.c"
  /* PERFORM P801-INICIALIZA THRU P801-EXIT */
  frame_ptr++;
  if (unlikely(frame_ptr == frame_overflow))
  	cob_fatal_error (COB_FERROR_STACK);
  frame_ptr->perform_through = 17;
  frame_ptr->return_address_ptr = &&l_26;
  goto l_16;
  l_26:
  frame_ptr--;

  /* Line: 96        : Paragraph P014-EXIT               : STRING.cbl */
#line 96 "STRING.cbl"
  PARAGRAPH_P014__EXIT_l_14:	cob_nop ();
#line 400 "STRING.c"

  /* Line: 97        : EXIT               : STRING.cbl */
#line 97 "STRING.cbl"
  cob_nop ();
#line 405 "STRING.c"

  /* Line: 99        : Paragraph S800-INICIALIZA         : STRING.cbl */
#line 99 "STRING.cbl"
  PARAGRAPH_S800__INICIALIZA_l_15:	cob_nop ();
#line 410 "STRING.c"

  /* Line: 100       : Paragraph P801-INICIALIZA         : STRING.cbl */
  l_16:;
#line 100 "STRING.cbl"
  PARAGRAPH_P801__INICIALIZA_l_16:	cob_nop ();
#line 416 "STRING.c"

  /* Line: 101       : INITIALIZE         : STRING.cbl */
#line 101 "STRING.cbl"
  cob_nop ();
#line 421 "STRING.c"
  memset (b_17, (unsigned char)' ', 45);
  memset (b_18, (unsigned char)' ', 45);
  memset (b_19, (unsigned char)'0', 2);

  /* Line: 105       : Paragraph P801-EXIT               : STRING.cbl */
  l_17:;
#line 105 "STRING.cbl"
  PARAGRAPH_P801__EXIT_l_17:	cob_nop ();
#line 430 "STRING.c"

  /* Line: 106       : EXIT               : STRING.cbl */
#line 106 "STRING.cbl"
  cob_nop ();
#line 435 "STRING.c"

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 17)
    goto *frame_ptr->return_address_ptr;

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 6)
    goto *frame_ptr->return_address_ptr;

  /* Line: 108       : Section   S900-TERMINO            : STRING.cbl */
#line 108 "STRING.cbl"
  SECTION_S900__TERMINO:	cob_nop ();
#line 448 "STRING.c"

  /* Line: 109       : Paragraph P901-TERM               : STRING.cbl */
  l_19:;
#line 109 "STRING.cbl"
  PARAGRAPH_P901__TERM_l_19:	cob_nop ();
#line 454 "STRING.c"

  /* Line: 110       : STOP RUN           : STRING.cbl */
#line 110 "STRING.cbl"
  cob_nop ();
#line 459 "STRING.c"
  cob_stop_run (b_2);

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 19)
    goto *frame_ptr->return_address_ptr;

  /* Line: 111       : Paragraph P901-EXIT               : STRING.cbl */
#line 111 "STRING.cbl"
  PARAGRAPH_P901__EXIT_l_20:	cob_nop ();
#line 469 "STRING.c"

  /* Line: 112       : EXIT               : STRING.cbl */
#line 112 "STRING.cbl"
  cob_nop ();
#line 474 "STRING.c"

  /* Program exit */

  exit_program:

  /* Decrement module active count */
  if (module->module_active) {
  	module->module_active--;
  }

  /* Pop module stack */
  cob_module_leave (module);

  /* Program return */
  return b_2;
  P_cgerror:
  	cob_fatal_error (COB_FERROR_CODEGEN);


  /* Program initialization */
  P_initialize:

  cob_module_path = cob_glob_ptr->cob_main_argv0;

  PGM__STRING_module_init (module);

  module->collating_sequence = NULL;
  module->crt_status = NULL;
  module->cursor_pos = NULL;
  module->xml_code = NULL;
  module->xml_event = NULL;
  module->xml_information = NULL;
  module->xml_namespace = NULL;
  module->xml_namespace_prefix = NULL;
  module->xml_nnamespace = NULL;
  module->xml_nnamespace_prefix = NULL;
  module->xml_ntext = NULL;
  module->xml_text = NULL;
  module->json_code = NULL;
  module->json_status = NULL;

  /* Initialize cancel callback */
  cob_set_cancel (module);

  /* Initialize WORKING-STORAGE */
  /* initialize field RETURN-CODE */
  b_2 = 0;

  /* initialize field WS-CONTEUDO */
#line 12 "STRING.cbl"
  cob_nop ();
#line 526 "STRING.c"
  memset (b_17, 32, 45);

  /* initialize field WS-TEXTO */
#line 13 "STRING.cbl"
  cob_nop ();
#line 532 "STRING.c"
  memset (b_18, 32, 45);

  /* initialize field WS-PONTEIRO */
#line 14 "STRING.cbl"
  cob_nop ();
#line 538 "STRING.c"
  memset (b_19, 48, 2);


  if (0 == 1) goto P_cgerror;
  initialized = 1;
  goto P_ret_initialize;

  P_dump:
    return 0;


  /* CANCEL callback handling */
  P_cancel:

  if (!initialized)
  	return 0;
  if (module && module->module_active)
  	cob_fatal_error (COB_FERROR_CANCEL);

  initialized = 0;

  P_clear_decimal:
  return 0;

}

/* End PROGRAM-ID 'PGM-STRING' */

/* Initialize module structure for PGM-STRING */
static void PGM__STRING_module_init (cob_module *module)
{
  module->module_name = "PGM-STRING";
  module->module_formatted_date = COB_MODULE_FORMATTED_DATE;
  module->module_source = COB_SOURCE_FILE;
  module->gc_version = COB_PACKAGE_VERSION;
  module->module_entry.funcptr = (void *(*)())PGM__STRING;
  module->module_cancel.funcptr = (void *(*)())PGM__STRING_;
  module->module_ref_count = NULL;
  module->module_path = &cob_module_path;
  module->module_active = 0;
  module->module_date = COB_MODULE_DATE;
  module->module_time = COB_MODULE_TIME;
  module->module_type = 0;
  module->module_param_cnt = 0;
  module->ebcdic_sign = 0;
  module->decimal_point = '.';
  module->currency_symbol = '$';
  module->numeric_separator = ',';
  module->flag_filename_mapping = 1;
  module->flag_binary_truncate = 1;
  module->flag_pretty_display = 1;
  module->flag_host_sign = 0;
  module->flag_no_phys_canc = 1;
  module->flag_main = 1;
  module->flag_fold_call = 0;
  module->flag_exit_program = 0;
  module->flag_debug_trace = 0;
  module->flag_dump_ready = 0;
  module->xml_mode = 1;
  module->module_stmt = 0;
  module->module_sources = NULL;
}

/* End functions */

